/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author valer
 */
public class FrmAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAdmin.class.getName());

    /**
     * Creates new form FrmAdmin
     */
    public FrmAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IblBienvenida = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        tabAdmin = new javax.swing.JTabbedPane();
        pnlTipos = new javax.swing.JPanel();
        scrTipos = new javax.swing.JScrollPane();
        tblTipos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNombreTipo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrefijoTipo = new javax.swing.JTextField();
        btnLimpiarTipo = new javax.swing.JButton();
        btnEliminarTipo = new javax.swing.JButton();
        btnActualizarTipo = new javax.swing.JButton();
        btnGuardarTipo = new javax.swing.JButton();
        pnlUsuarios = new javax.swing.JPanel();
        scrUsuarios = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtCedulaUsu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoUsu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombreUsu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pwdContrasenaUsu = new javax.swing.JPasswordField();
        cmbTipoUsu = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        chkActivoUsu = new javax.swing.JCheckBox();
        btnGuardarUsu = new javax.swing.JButton();
        btnActualizarUsu = new javax.swing.JButton();
        btnContrasenaUsu = new javax.swing.JButton();
        btnEliminarUsu = new javax.swing.JButton();
        btnLimpiarUsu = new javax.swing.JButton();
        pnlSecciones = new javax.swing.JPanel();
        scrSecciones = new javax.swing.JScrollPane();
        tblSecciones = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtNombreSec = new javax.swing.JTextField();
        btnGuardarSec = new javax.swing.JButton();
        btnActualizarSec = new javax.swing.JButton();
        btnEliminarSec = new javax.swing.JButton();
        btnLimpiarSec = new javax.swing.JButton();
        pnlMesas = new javax.swing.JPanel();
        scrMesas = new javax.swing.JScrollPane();
        tblMesas = new javax.swing.JTable();
        spnNumeroMesa = new javax.swing.JSpinner();
        cmbSeccionMesa = new javax.swing.JComboBox<>();
        chkDisponibleMesa = new javax.swing.JCheckBox();
        btnGuardarMesa = new javax.swing.JButton();
        btnActualizarMesa = new javax.swing.JButton();
        btnEliminarMesa = new javax.swing.JButton();
        btnLimpiarMesa = new javax.swing.JButton();
        pnlComidas = new javax.swing.JPanel();
        scrComidas = new javax.swing.JScrollPane();
        tblComidas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtNombreComida = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbCategoriaComida = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtPrecioComida = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDescripcionComida = new javax.swing.JTextField();
        chkActivoComida = new javax.swing.JCheckBox();
        btnGuardarComida = new javax.swing.JButton();
        btnActualizarComida = new javax.swing.JButton();
        btnEliminarComida = new javax.swing.JButton();
        btnLimpiarComida = new javax.swing.JButton();
        pnlBebidas = new javax.swing.JPanel();
        scrBebidas = new javax.swing.JScrollPane();
        tblBebidas = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtNombreBebida = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmbCategoriaBebida = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtPrecioBebida = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDescripcionBebida = new javax.swing.JTextField();
        chkActivoBebida = new javax.swing.JCheckBox();
        btnGuardarBebida = new javax.swing.JButton();
        btnActualizarBebida = new javax.swing.JButton();
        btnEliminarBebida = new javax.swing.JButton();
        btnLimpiarBebida = new javax.swing.JButton();
        pnlCategorias = new javax.swing.JPanel();
        scrCatComida = new javax.swing.JScrollPane();
        tblCatComida = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        txtNombreCatComida = new javax.swing.JTextField();
        btnGuardarCatComida = new javax.swing.JButton();
        btnActualizarCatComida = new javax.swing.JButton();
        btnEliminarCatComida = new javax.swing.JButton();
        btnLimpiarCatComida = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        scrCatBebida = new javax.swing.JScrollPane();
        tblCatBebida = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txtNombreCatBebida = new javax.swing.JTextField();
        btnGuardarCatBebida = new javax.swing.JButton();
        btnActualizarCatBebida = new javax.swing.JButton();
        btnEliminarCatBebida = new javax.swing.JButton();
        btnLimpiarCatBebida = new javax.swing.JButton();
        pnlRotacion = new javax.swing.JPanel();
        scrRotacion = new javax.swing.JScrollPane();
        tblRotacion = new javax.swing.JTable();
        cmbSaloneroRot = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cmbSeccionRot = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtFechaRot = new javax.swing.JTextField();
        btnGuardarRot = new javax.swing.JButton();
        btnEliminarRot = new javax.swing.JButton();
        btnLimpiarRot = new javax.swing.JButton();
        pnlReportes = new javax.swing.JPanel();
        cmbTipoReporte = new javax.swing.JComboBox<>();
        btnGenerarReporte = new javax.swing.JButton();
        pnlGrafico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IblBienvenida.setText("Admin: Administrador General");

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");

        tabAdmin.setPreferredSize(new java.awt.Dimension(705, 100));

        tblTipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Prefijo"
            }
        ));
        scrTipos.setViewportView(tblTipos);
        if (tblTipos.getColumnModel().getColumnCount() > 0) {
            tblTipos.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Prefijo:");

        btnLimpiarTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiarTipo.setText("Limpiar");

        btnEliminarTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarTipo.setText("Eliminar");

        btnActualizarTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarTipo.setText("Actualizar");

        btnGuardarTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarTipo.setText("Guardar");

        javax.swing.GroupLayout pnlTiposLayout = new javax.swing.GroupLayout(pnlTipos);
        pnlTipos.setLayout(pnlTiposLayout);
        pnlTiposLayout.setHorizontalGroup(
            pnlTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTiposLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTiposLayout.createSequentialGroup()
                        .addGroup(pnlTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlTiposLayout.createSequentialGroup()
                        .addGroup(pnlTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPrefijoTipo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTiposLayout.createSequentialGroup()
                                .addComponent(btnGuardarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(btnActualizarTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(btnEliminarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombreTipo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        pnlTiposLayout.setVerticalGroup(
            pnlTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTiposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(txtNombreTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtPrefijoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(pnlTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarTipo)
                    .addComponent(btnActualizarTipo)
                    .addComponent(btnEliminarTipo)
                    .addComponent(btnLimpiarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        tabAdmin.addTab("Tipos", pnlTipos);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre ", "Tipo", "Activo"
            }
        ));
        scrUsuarios.setViewportView(tblUsuarios);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Cédula:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Código:");

        txtCodigoUsu.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nombre:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Contraseña:");

        pwdContrasenaUsu.setText("jPasswordField1");

        cmbTipoUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tipo:");

        chkActivoUsu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkActivoUsu.setSelected(true);
        chkActivoUsu.setText("Activo");

        btnGuardarUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarUsu.setText("Guardar");

        btnActualizarUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizarUsu.setText("Actualizar");

        btnContrasenaUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnContrasenaUsu.setText("Contraseña");

        btnEliminarUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarUsu.setText("Eliminar");

        btnLimpiarUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiarUsu.setText("Limpiar");

        javax.swing.GroupLayout pnlUsuariosLayout = new javax.swing.GroupLayout(pnlUsuarios);
        pnlUsuarios.setLayout(pnlUsuariosLayout);
        pnlUsuariosLayout.setHorizontalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUsuariosLayout.createSequentialGroup()
                        .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrUsuarios)
                            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUsuariosLayout.createSequentialGroup()
                                        .addComponent(txtNombreUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72))
                                    .addGroup(pnlUsuariosLayout.createSequentialGroup()
                                        .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                                                .addComponent(txtCodigoUsu)
                                                .addGap(147, 147, 147))
                                            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                                                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCedulaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)))
                                        .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pwdContrasenaUsu, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                            .addComponent(cmbTipoUsu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuariosLayout.createSequentialGroup()
                                .addComponent(chkActivoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addComponent(btnGuardarUsu)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizarUsu)
                                .addGap(18, 18, 18)
                                .addComponent(btnContrasenaUsu)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarUsu)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiarUsu)
                                .addGap(13, 13, 13)))
                        .addContainerGap())
                    .addGroup(pnlUsuariosLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(212, 212, 212))
                    .addGroup(pnlUsuariosLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlUsuariosLayout.setVerticalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdContrasenaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8)
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUsuariosLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarUsu)
                            .addComponent(btnActualizarUsu)
                            .addComponent(btnContrasenaUsu)
                            .addComponent(btnEliminarUsu)
                            .addComponent(btnLimpiarUsu)))
                    .addGroup(pnlUsuariosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkActivoUsu)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tabAdmin.addTab("Usuarios", pnlUsuarios);

        tblSecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        scrSecciones.setViewportView(tblSecciones);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Nombre:");

        btnGuardarSec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarSec.setText("Guardar");

        btnActualizarSec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarSec.setText("Actualizar");

        btnEliminarSec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarSec.setText("Eliminar");

        btnLimpiarSec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiarSec.setText("Limpiar");

        javax.swing.GroupLayout pnlSeccionesLayout = new javax.swing.GroupLayout(pnlSecciones);
        pnlSecciones.setLayout(pnlSeccionesLayout);
        pnlSeccionesLayout.setHorizontalGroup(
            pnlSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeccionesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrSecciones)
                    .addGroup(pnlSeccionesLayout.createSequentialGroup()
                        .addGroup(pnlSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSeccionesLayout.createSequentialGroup()
                                .addComponent(btnGuardarSec, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(btnActualizarSec)
                                .addGap(61, 61, 61)
                                .addComponent(btnEliminarSec, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(btnLimpiarSec, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlSeccionesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnlSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreSec, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlSeccionesLayout.setVerticalGroup(
            pnlSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeccionesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(scrSecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(pnlSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarSec)
                    .addComponent(btnActualizarSec)
                    .addComponent(btnEliminarSec)
                    .addComponent(btnLimpiarSec))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        tabAdmin.addTab("Secciones", pnlSecciones);

        tblMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Número", "Sección", "Disponible "
            }
        ));
        scrMesas.setViewportView(tblMesas);

        spnNumeroMesa.setModel(new javax.swing.SpinnerNumberModel(1, 1, 18, 1));

        cmbSeccionMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sección A", "Sección B", "Sección C" }));

        chkDisponibleMesa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkDisponibleMesa.setSelected(true);
        chkDisponibleMesa.setText("Disponible");

        btnGuardarMesa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarMesa.setText("Guardar");

        btnActualizarMesa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarMesa.setText("Actualizar");

        btnEliminarMesa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarMesa.setText("Eliminar");

        btnLimpiarMesa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiarMesa.setText("Limpiar");

        javax.swing.GroupLayout pnlMesasLayout = new javax.swing.GroupLayout(pnlMesas);
        pnlMesas.setLayout(pnlMesasLayout);
        pnlMesasLayout.setHorizontalGroup(
            pnlMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMesasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMesasLayout.createSequentialGroup()
                        .addComponent(scrMesas)
                        .addContainerGap())
                    .addGroup(pnlMesasLayout.createSequentialGroup()
                        .addComponent(btnGuardarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnActualizarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(btnEliminarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(pnlMesasLayout.createSequentialGroup()
                        .addComponent(spnNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(pnlMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMesasLayout.createSequentialGroup()
                                .addComponent(chkDisponibleMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlMesasLayout.createSequentialGroup()
                                .addComponent(cmbSeccionMesa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))))))
        );
        pnlMesasLayout.setVerticalGroup(
            pnlMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMesasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(pnlMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSeccionMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDisponibleMesa)
                .addGap(40, 40, 40)
                .addGroup(pnlMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarMesa)
                    .addComponent(btnActualizarMesa)
                    .addComponent(btnEliminarMesa)
                    .addComponent(btnLimpiarMesa))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        tabAdmin.addTab("Mesas", pnlMesas);

        tblComidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre ", "Categoría", "Precio", "Activo"
            }
        ));
        scrComidas.setViewportView(tblComidas);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Nombre:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Categoría:");

        cmbCategoriaComida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ensalada", "Plato Fuerte", "Postre", "Comida Rápida" }));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Precio:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Descripción:");

        chkActivoComida.setSelected(true);
        chkActivoComida.setText("Activo");

        btnGuardarComida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarComida.setText("Guardar");

        btnActualizarComida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarComida.setText("Actualizar");

        btnEliminarComida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarComida.setText("Eliminar");

        btnLimpiarComida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiarComida.setText("Limpiar");

        javax.swing.GroupLayout pnlComidasLayout = new javax.swing.GroupLayout(pnlComidas);
        pnlComidas.setLayout(pnlComidasLayout);
        pnlComidasLayout.setHorizontalGroup(
            pnlComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlComidasLayout.createSequentialGroup()
                        .addComponent(scrComidas)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlComidasLayout.createSequentialGroup()
                        .addComponent(chkActivoComida, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlComidasLayout.createSequentialGroup()
                        .addGroup(pnlComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtNombreComida, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(cmbCategoriaComida, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecioComida, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89))))
            .addGroup(pnlComidasLayout.createSequentialGroup()
                .addGroup(pnlComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlComidasLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnGuardarComida)
                        .addGap(43, 43, 43)
                        .addComponent(btnActualizarComida)
                        .addGap(49, 49, 49)
                        .addComponent(btnEliminarComida)
                        .addGap(42, 42, 42)
                        .addComponent(btnLimpiarComida))
                    .addGroup(pnlComidasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtDescripcionComida, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        pnlComidasLayout.setVerticalGroup(
            pnlComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrComidas, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategoriaComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcionComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkActivoComida)
                .addGap(18, 18, 18)
                .addGroup(pnlComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarComida)
                    .addComponent(btnActualizarComida)
                    .addComponent(btnEliminarComida)
                    .addComponent(btnLimpiarComida))
                .addGap(17, 17, 17))
        );

        tabAdmin.addTab("Comidas", pnlComidas);

        tblBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Categoría ", "Precio", "Activo "
            }
        ));
        scrBebidas.setViewportView(tblBebidas);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Nombre:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Categoría:");

        cmbCategoriaBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebida Fría ", "Bebida Caliente ", "Malteada", "Licor " }));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Precio:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Descripción:");

        chkActivoBebida.setSelected(true);
        chkActivoBebida.setText("Activo");

        btnGuardarBebida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarBebida.setText("Guardar");

        btnActualizarBebida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizarBebida.setText("Actualizar");

        btnEliminarBebida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarBebida.setText("Eliminar");

        btnLimpiarBebida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiarBebida.setText("Limpiar");

        javax.swing.GroupLayout pnlBebidasLayout = new javax.swing.GroupLayout(pnlBebidas);
        pnlBebidas.setLayout(pnlBebidasLayout);
        pnlBebidasLayout.setHorizontalGroup(
            pnlBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBebidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrBebidas)
                    .addGroup(pnlBebidasLayout.createSequentialGroup()
                        .addGroup(pnlBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(txtNombreBebida)
                                .addGroup(pnlBebidasLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(313, 313, 313)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlBebidasLayout.createSequentialGroup()
                                    .addComponent(cmbCategoriaBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(105, 105, 105)
                                    .addComponent(txtPrecioBebida, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                                .addComponent(txtDescripcionBebida))
                            .addComponent(chkActivoBebida))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlBebidasLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btnGuardarBebida)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarBebida)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarBebida)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarBebida)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        pnlBebidasLayout.setVerticalGroup(
            pnlBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBebidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(4, 4, 4)
                .addGroup(pnlBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategoriaBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcionBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkActivoBebida)
                .addGap(18, 18, 18)
                .addGroup(pnlBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarBebida)
                    .addComponent(btnActualizarBebida)
                    .addComponent(btnEliminarBebida)
                    .addComponent(btnLimpiarBebida))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tabAdmin.addTab("Bebidas", pnlBebidas);

        tblCatComida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        scrCatComida.setViewportView(tblCatComida);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Nombre:");

        btnGuardarCatComida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarCatComida.setText("Guardar");

        btnActualizarCatComida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarCatComida.setText("Actualizar");

        btnEliminarCatComida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarCatComida.setText("Eliminar");

        btnLimpiarCatComida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiarCatComida.setText("Limpiar");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tblCatBebida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        scrCatBebida.setViewportView(tblCatBebida);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Nombre:");

        btnGuardarCatBebida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarCatBebida.setText("Guardar");

        btnActualizarCatBebida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarCatBebida.setText("Actualizar");

        btnEliminarCatBebida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarCatBebida.setText("Eliminar");

        btnLimpiarCatBebida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiarCatBebida.setText("Limpiar");

        javax.swing.GroupLayout pnlCategoriasLayout = new javax.swing.GroupLayout(pnlCategorias);
        pnlCategorias.setLayout(pnlCategoriasLayout);
        pnlCategoriasLayout.setHorizontalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addComponent(btnLimpiarCatComida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarCatComida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardarCatComida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarCatComida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrCatComida, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(txtNombreCatComida))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrCatBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtNombreCatBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnLimpiarCatBebida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarCatBebida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarCatBebida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizarCatBebida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        pnlCategoriasLayout.setVerticalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(pnlCategoriasLayout.createSequentialGroup()
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                                .addComponent(scrCatComida, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreCatComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardarCatComida)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizarCatComida)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarCatComida)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiarCatComida))
                            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                                .addComponent(scrCatBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreCatBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardarCatBebida)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizarCatBebida)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarCatBebida)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiarCatBebida)))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabAdmin.addTab("Categorías", pnlCategorias);

        tblRotacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Salonero", "Sección", "Fecha"
            }
        ));
        scrRotacion.setViewportView(tblRotacion);

        cmbSaloneroRot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ana Solís (SAL001)", "Luis Mora (SAL002)", "Carmen Vega (SAL003)" }));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Salonero:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Sección:");

        cmbSeccionRot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sección A ", "Sección B ", "Sección C " }));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Fecha:");

        btnGuardarRot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarRot.setText("Guardar");

        btnEliminarRot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarRot.setText("Eliminar");

        btnLimpiarRot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiarRot.setText("Limpiar");

        javax.swing.GroupLayout pnlRotacionLayout = new javax.swing.GroupLayout(pnlRotacion);
        pnlRotacion.setLayout(pnlRotacionLayout);
        pnlRotacionLayout.setHorizontalGroup(
            pnlRotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRotacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrRotacion)
                .addContainerGap())
            .addGroup(pnlRotacionLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRotacionLayout.createSequentialGroup()
                .addGroup(pnlRotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRotacionLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(cmbSaloneroRot, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(cmbSeccionRot, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRotacionLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnGuardarRot)
                        .addGap(83, 83, 83)
                        .addComponent(btnEliminarRot)))
                .addGroup(pnlRotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRotacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(txtFechaRot, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(pnlRotacionLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnLimpiarRot)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlRotacionLayout.setVerticalGroup(
            pnlRotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRotacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrRotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(pnlRotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(pnlRotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSeccionRot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaRot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSaloneroRot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(pnlRotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarRot)
                    .addComponent(btnEliminarRot)
                    .addComponent(btnLimpiarRot))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        tabAdmin.addTab("Rotación ", pnlRotacion);

        cmbTipoReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbTipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personas atendidas por día - Salón", "Personas atendidas por día - Bar ", "Comandas realizadas en el Bar ", "Comandas atendidas en el Bar", "Comandas atendidas en Cocina (Salón vs Bar)" }));

        btnGenerarReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerarReporte.setText("Generar Reporte ");

        javax.swing.GroupLayout pnlGraficoLayout = new javax.swing.GroupLayout(pnlGrafico);
        pnlGrafico.setLayout(pnlGraficoLayout);
        pnlGraficoLayout.setHorizontalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlGraficoLayout.setVerticalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlReportesLayout = new javax.swing.GroupLayout(pnlReportes);
        pnlReportes.setLayout(pnlReportesLayout);
        pnlReportesLayout.setHorizontalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReportesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlReportesLayout.createSequentialGroup()
                        .addComponent(cmbTipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(btnGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        pnlReportesLayout.setVerticalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarReporte))
                .addGap(18, 18, 18)
                .addComponent(pnlGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        tabAdmin.addTab("Reportes", pnlReportes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(IblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblBienvenida)
                    .addComponent(btnCerrarSesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblBienvenida;
    private javax.swing.JButton btnActualizarBebida;
    private javax.swing.JButton btnActualizarCatBebida;
    private javax.swing.JButton btnActualizarCatComida;
    private javax.swing.JButton btnActualizarComida;
    private javax.swing.JButton btnActualizarMesa;
    private javax.swing.JButton btnActualizarSec;
    private javax.swing.JButton btnActualizarTipo;
    private javax.swing.JButton btnActualizarUsu;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnContrasenaUsu;
    private javax.swing.JButton btnEliminarBebida;
    private javax.swing.JButton btnEliminarCatBebida;
    private javax.swing.JButton btnEliminarCatComida;
    private javax.swing.JButton btnEliminarComida;
    private javax.swing.JButton btnEliminarMesa;
    private javax.swing.JButton btnEliminarRot;
    private javax.swing.JButton btnEliminarSec;
    private javax.swing.JButton btnEliminarTipo;
    private javax.swing.JButton btnEliminarUsu;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnGuardarBebida;
    private javax.swing.JButton btnGuardarCatBebida;
    private javax.swing.JButton btnGuardarCatComida;
    private javax.swing.JButton btnGuardarComida;
    private javax.swing.JButton btnGuardarMesa;
    private javax.swing.JButton btnGuardarRot;
    private javax.swing.JButton btnGuardarSec;
    private javax.swing.JButton btnGuardarTipo;
    private javax.swing.JButton btnGuardarUsu;
    private javax.swing.JButton btnLimpiarBebida;
    private javax.swing.JButton btnLimpiarCatBebida;
    private javax.swing.JButton btnLimpiarCatComida;
    private javax.swing.JButton btnLimpiarComida;
    private javax.swing.JButton btnLimpiarMesa;
    private javax.swing.JButton btnLimpiarRot;
    private javax.swing.JButton btnLimpiarSec;
    private javax.swing.JButton btnLimpiarTipo;
    private javax.swing.JButton btnLimpiarUsu;
    private javax.swing.JCheckBox chkActivoBebida;
    private javax.swing.JCheckBox chkActivoComida;
    private javax.swing.JCheckBox chkActivoUsu;
    private javax.swing.JCheckBox chkDisponibleMesa;
    private javax.swing.JComboBox<String> cmbCategoriaBebida;
    private javax.swing.JComboBox<String> cmbCategoriaComida;
    private javax.swing.JComboBox<String> cmbSaloneroRot;
    private javax.swing.JComboBox<String> cmbSeccionMesa;
    private javax.swing.JComboBox<String> cmbSeccionRot;
    private javax.swing.JComboBox<String> cmbTipoReporte;
    private javax.swing.JComboBox<String> cmbTipoUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlBebidas;
    private javax.swing.JPanel pnlCategorias;
    private javax.swing.JPanel pnlComidas;
    private javax.swing.JPanel pnlGrafico;
    private javax.swing.JPanel pnlMesas;
    private javax.swing.JPanel pnlReportes;
    private javax.swing.JPanel pnlRotacion;
    private javax.swing.JPanel pnlSecciones;
    private javax.swing.JPanel pnlTipos;
    private javax.swing.JPanel pnlUsuarios;
    private javax.swing.JPasswordField pwdContrasenaUsu;
    private javax.swing.JScrollPane scrBebidas;
    private javax.swing.JScrollPane scrCatBebida;
    private javax.swing.JScrollPane scrCatComida;
    private javax.swing.JScrollPane scrComidas;
    private javax.swing.JScrollPane scrMesas;
    private javax.swing.JScrollPane scrRotacion;
    private javax.swing.JScrollPane scrSecciones;
    private javax.swing.JScrollPane scrTipos;
    private javax.swing.JScrollPane scrUsuarios;
    private javax.swing.JSpinner spnNumeroMesa;
    private javax.swing.JTabbedPane tabAdmin;
    private javax.swing.JTable tblBebidas;
    private javax.swing.JTable tblCatBebida;
    private javax.swing.JTable tblCatComida;
    private javax.swing.JTable tblComidas;
    private javax.swing.JTable tblMesas;
    private javax.swing.JTable tblRotacion;
    private javax.swing.JTable tblSecciones;
    private javax.swing.JTable tblTipos;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtCedulaUsu;
    private javax.swing.JTextField txtCodigoUsu;
    private javax.swing.JTextField txtDescripcionBebida;
    private javax.swing.JTextField txtDescripcionComida;
    private javax.swing.JTextField txtFechaRot;
    private javax.swing.JTextField txtNombreBebida;
    private javax.swing.JTextField txtNombreCatBebida;
    private javax.swing.JTextField txtNombreCatComida;
    private javax.swing.JTextField txtNombreComida;
    private javax.swing.JTextField txtNombreSec;
    private javax.swing.JTextField txtNombreTipo;
    private javax.swing.JTextField txtNombreUsu;
    private javax.swing.JTextField txtPrecioBebida;
    private javax.swing.JTextField txtPrecioComida;
    private javax.swing.JTextField txtPrefijoTipo;
    // End of variables declaration//GEN-END:variables
}
