/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import dao.BebidaDAO;
import dao.ComandaDAO;
import dao.ComidaDAO;
import dao.DetalleComandaDAO;
import dao.MesaDAO;
import dao.ProcesoBarDAO;
import dao.ProcesoCocinaDAO;
import java.math.BigDecimal;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bebida;
import model.Comanda;
import model.Comida;
import model.DetalleComanda;
import model.Mesa;
import model.ProcesoBar;
import model.ProcesoCocina;
import session.SesionActual;

/**
 * Bar screen: it serves the pending drinks and can create its own orders.
 *
 * @author valer
 */
public class FrmBartender extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmBartender.class.getName());

    // an order has 20 minutes to be served
    private static final int LIMITE_MINUTOS = 20;

    private final ProcesoBarDAO barDAO = new ProcesoBarDAO();
    private final ProcesoCocinaDAO cocinaDAO = new ProcesoCocinaDAO();
    private final ComandaDAO comandaDAO = new ComandaDAO();
    private final DetalleComandaDAO detalleDAO = new DetalleComandaDAO();
    private final BebidaDAO bebidaDAO = new BebidaDAO();
    private final ComidaDAO comidaDAO = new ComidaDAO();
    private final MesaDAO mesaDAO = new MesaDAO();

    private final DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    private List<ProcesoBar> pendientes = new ArrayList<>();

    /**
     * Creates new form FrmBartender
     */
    public FrmBartender() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Restaurante - Bar");

        tblComandasBar.setDefaultEditor(Object.class, null);
        tblDetalleComandaBar.setDefaultEditor(Object.class, null);

        if (SesionActual.getUsuario() != null) {
            IblBienvenidaBar.setText("Bar: " + SesionActual.getNombre());
        }
        cargarPendientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IblBienvenidaBar = new javax.swing.JLabel();
        btnCerrarSesionBar = new javax.swing.JButton();
        scrComandasBar = new javax.swing.JScrollPane();
        tblComandasBar = new javax.swing.JTable();
        scrDetalleBar = new javax.swing.JScrollPane();
        tblDetalleComandaBar = new javax.swing.JTable();
        btnVerDetalleBar = new javax.swing.JButton();
        btnCrearComandaBar = new javax.swing.JButton();
        btnMarcarListaBar = new javax.swing.JButton();
        btnRefrescarBar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IblBienvenidaBar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IblBienvenidaBar.setText("Bar: Diego Campos ");

        btnCerrarSesionBar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesionBar.setText("Cerrar Sesion ");
        btnCerrarSesionBar.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnCerrarSesionBarActionPerformed(evt);
        });

        tblComandasBar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número Comandas ", "Origen ", "Mesa ", "Hora Recibida", "Estado "
            }
        ));
        scrComandasBar.setViewportView(tblComandasBar);

        tblDetalleComandaBar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ítem", "Tipo", "Cantidad "
            }
        ));
        scrDetalleBar.setViewportView(tblDetalleComandaBar);

        btnVerDetalleBar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerDetalleBar.setText("Detalle Bar");
        btnVerDetalleBar.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnVerDetalleBarActionPerformed(evt);
        });

        btnCrearComandaBar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCrearComandaBar.setText("Crear Comanda");
        btnCrearComandaBar.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnCrearComandaBarActionPerformed(evt);
        });

        btnMarcarListaBar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMarcarListaBar.setText("Marcar Lista Bar");
        btnMarcarListaBar.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnMarcarListaBarActionPerformed(evt);
        });

        btnRefrescarBar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefrescarBar.setText("Refrescar Bar");
        btnRefrescarBar.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnRefrescarBarActionPerformed(evt);
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerDetalleBar)
                .addGap(18, 18, 18)
                .addComponent(btnCrearComandaBar)
                .addGap(18, 18, 18)
                .addComponent(btnMarcarListaBar)
                .addGap(18, 18, 18)
                .addComponent(btnRefrescarBar)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrDetalleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(IblBienvenidaBar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCerrarSesionBar))
                        .addComponent(scrComandasBar, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSesionBar)
                    .addComponent(IblBienvenidaBar))
                .addGap(18, 18, 18)
                .addComponent(scrComandasBar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrDetalleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerDetalleBar)
                    .addComponent(btnCrearComandaBar)
                    .addComponent(btnMarcarListaBar)
                    .addComponent(btnRefrescarBar))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionBarActionPerformed
        SesionActual.cerrarSesion();
        new FrmLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionBarActionPerformed

    private void btnRefrescarBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarBarActionPerformed
        cargarPendientes();
    }//GEN-LAST:event_btnRefrescarBarActionPerformed

    private void btnVerDetalleBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleBarActionPerformed
        verDetalle();
    }//GEN-LAST:event_btnVerDetalleBarActionPerformed

    private void btnMarcarListaBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarListaBarActionPerformed
        marcarLista();
    }//GEN-LAST:event_btnMarcarListaBarActionPerformed

    private void btnCrearComandaBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearComandaBarActionPerformed
        crearComandaBar();
    }//GEN-LAST:event_btnCrearComandaBarActionPerformed

    /** Loads the orders with drinks the bar has not delivered yet. */
    private void cargarPendientes() {
        pendientes = barDAO.findPendientes();
        List<Mesa> todasLasMesas = mesaDAO.findAll();

        DefaultTableModel modelo = (DefaultTableModel) tblComandasBar.getModel();
        modelo.setRowCount(0);

        for (ProcesoBar p : pendientes) {
            Comanda c = comandaDAO.findById(p.getId_comanda());
            if (c == null) {
                continue;
            }
            String hora = p.getHora_recibida() != null ? p.getHora_recibida().format(formatoHora) : "";
            String estado = c.getEstado();
            if (minutosEsperando(p) > LIMITE_MINUTOS) {
                estado = estado + " (atrasada)";
            }
            modelo.addRow(new Object[]{c.getId_comanda(), c.getORIGEN(), nombreMesa(todasLasMesas, c.getId_mesa()), hora, estado});
        }

        ((DefaultTableModel) tblDetalleComandaBar.getModel()).setRowCount(0);
    }

    /** Shows only the drinks of the selected order. */
    private void verDetalle() {
        int fila = tblComandasBar.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una comanda de la lista.");
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tblDetalleComandaBar.getModel();
        modelo.setRowCount(0);

        List<DetalleComanda> detalles = detalleDAO.findByComanda(pendientes.get(fila).getId_comanda());
        for (DetalleComanda d : detalles) {
            if ("bebida".equals(d.getTipo_item())) {
                modelo.addRow(new Object[]{detalleDAO.getNombreItem(d), d.getTipo_item(), d.getCantidad()});
            }
        }
    }

    /** Marks the drinks as ready and checks whether the kitchen is done. */
    private void marcarLista() {
        int fila = tblComandasBar.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una comanda de la lista.");
            return;
        }

        ProcesoBar proceso = pendientes.get(fila);
        proceso.setHora_lista(LocalDateTime.now());
        proceso.setCodigo_bar(SesionActual.getCodigo());

        if (!barDAO.update(proceso)) {
            JOptionPane.showMessageDialog(this, "No se pudo marcar la comanda.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // the order becomes ready only when the kitchen finished its part too
        ProcesoCocina procesoCocina = cocinaDAO.findByComanda(proceso.getId_comanda());
        if (procesoCocina == null || procesoCocina.getHora_lista() != null) {
            comandaDAO.updateEstado(proceso.getId_comanda(), "lista");
            JOptionPane.showMessageDialog(this, "Comanda #" + proceso.getId_comanda() + " lista para servir.");
        } else {
            comandaDAO.updateEstado(proceso.getId_comanda(), "en_proceso");
            JOptionPane.showMessageDialog(this, "Bebidas listas. Falta que la cocina termine los platos.");
        }

        cargarPendientes();
    }

    /**
     * Creates a bar order, which has no table. A bar customer may order drinks
     * and food as well; the food part is sent to the kitchen.
     */
    private void crearComandaBar() {
        List<DetalleComanda> nuevaOrden = new ArrayList<>();

        // ask item by item until the user cancels or answers no
        while (true) {
            Object[] opciones = {"Bebida", "Comida"};
            int cual = JOptionPane.showOptionDialog(this, "¿Qué va a agregar?", "Comanda del bar",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
            if (cual != 0 && cual != 1) {
                break; // the dialog was closed
            }
            boolean esBebida = (cual == 0);

            String codigo = JOptionPane.showInputDialog(this,
                    esBebida ? "Código de la bebida:" : "Código del plato:");
            if (codigo == null) {
                break;
            }

            String nombre;
            int idItem;
            BigDecimal precio;
            if (esBebida) {
                Bebida bebida = bebidaDAO.findById(leerEntero(codigo));
                if (bebida == null) {
                    JOptionPane.showMessageDialog(this, "No existe una bebida con ese código.");
                    continue;
                }
                if (bebida.getActivo() == 0) {
                    JOptionPane.showMessageDialog(this, "Esa bebida no está disponible hoy.");
                    continue;
                }
                nombre = bebida.getNombre();
                idItem = bebida.getId_bebida();
                precio = bebida.getPrecio();
            } else {
                Comida comida = comidaDAO.findById(leerEntero(codigo));
                if (comida == null) {
                    JOptionPane.showMessageDialog(this, "No existe una comida con ese código.");
                    continue;
                }
                if (comida.getActivo() == 0) {
                    JOptionPane.showMessageDialog(this, "Ese plato no está disponible hoy.");
                    continue;
                }
                nombre = comida.getNombre();
                idItem = comida.getId_comida();
                precio = comida.getPrecio();
            }

            String cantidadTexto = JOptionPane.showInputDialog(this, "Cantidad de " + nombre + ":", "1");
            if (cantidadTexto == null) {
                continue;
            }
            int cantidad = leerEntero(cantidadTexto);
            if (cantidad < 1) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser un número mayor a cero.");
                continue;
            }

            DetalleComanda detalle = new DetalleComanda();
            detalle.setTipo_item(esBebida ? "bebida" : "comida");
            detalle.setId_item(idItem);
            detalle.setCantidad(cantidad);
            detalle.setPrecio_unit(precio);
            nuevaOrden.add(detalle);

            int otra = JOptionPane.showConfirmDialog(this, "¿Agregar algo más?", "Comanda del bar", JOptionPane.YES_NO_OPTION);
            if (otra != JOptionPane.YES_OPTION) {
                break;
            }
        }

        if (nuevaOrden.isEmpty()) {
            return;
        }

        Comanda comanda = new Comanda();
        comanda.setORIGEN("bar");
        comanda.setCodigo_emp(SesionActual.getCodigo());
        comanda.setId_mesa(0); // bar orders have no table
        comanda.setHora_orden(LocalDateTime.now());
        comanda.setEstado("abierta");

        int idComanda = comandaDAO.insertGetId(comanda);
        if (idComanda <= 0) {
            JOptionPane.showMessageDialog(this, "No se pudo crear la comanda.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean hayComida = false;
        boolean hayBebida = false;
        for (DetalleComanda d : nuevaOrden) {
            d.setId_comanda(idComanda);
            detalleDAO.insert(d);
            if ("comida".equals(d.getTipo_item())) {
                hayComida = true;
            } else {
                hayBebida = true;
            }
        }

        if (hayBebida) {
            ProcesoBar proceso = new ProcesoBar();
            proceso.setId_comanda(idComanda);
            proceso.setHora_recibida(LocalDateTime.now());
            barDAO.insert(proceso);
        }
        // whatever was ordered to eat goes to the kitchen, just like a dining room order
        if (hayComida) {
            ProcesoCocina proceso = new ProcesoCocina();
            proceso.setId_comanda(idComanda);
            proceso.setHora_recibida(LocalDateTime.now());
            cocinaDAO.insert(proceso);
        }

        String aviso = "Comanda #" + idComanda + " creada con " + nuevaOrden.size() + " ítem(s).";
        if (hayComida) {
            aviso = aviso + "\nLa comida se mandó a la cocina.";
        }
        JOptionPane.showMessageDialog(this, aviso);
        cargarPendientes();
    }

    /** Minutes the order has been waiting in the bar. */
    private long minutosEsperando(ProcesoBar proceso) {
        if (proceso.getHora_recibida() == null) {
            return 0;
        }
        return Duration.between(proceso.getHora_recibida(), LocalDateTime.now()).toMinutes();
    }

    /** Finds the table number, so the raw id is not displayed. */
    private String nombreMesa(List<Mesa> lista, int idMesa) {
        for (Mesa m : lista) {
            if (m.getId_mesa() == idMesa) {
                return "Mesa " + m.getNumero_mesa();
            }
        }
        return "-";
    }

    /** Converts the text into a number, or -1 when it is not a number. */
    private int leerEntero(String texto) {
        try {
            return Integer.parseInt(texto.trim());
        } catch (NumberFormatException e) {
            return -1;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmBartender().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblBienvenidaBar;
    private javax.swing.JButton btnCerrarSesionBar;
    private javax.swing.JButton btnCrearComandaBar;
    private javax.swing.JButton btnMarcarListaBar;
    private javax.swing.JButton btnRefrescarBar;
    private javax.swing.JButton btnVerDetalleBar;
    private javax.swing.JScrollPane scrComandasBar;
    private javax.swing.JScrollPane scrDetalleBar;
    private javax.swing.JTable tblComandasBar;
    private javax.swing.JTable tblDetalleComandaBar;
    // End of variables declaration//GEN-END:variables
}
