/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author valer
 */
public class FrmBartender extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmBartender.class.getName());

    /**
     * Creates new form FrmBartender
     */
    public FrmBartender() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IblBienvenidaBar = new javax.swing.JLabel();
        btnCerrarSesionBar = new javax.swing.JButton();
        scrComandasBar = new javax.swing.JScrollPane();
        tblComandasBar = new javax.swing.JTable();
        scrDetalleBar = new javax.swing.JScrollPane();
        tblDetalleComandaBar = new javax.swing.JTable();
        btnVerDetalleBar = new javax.swing.JButton();
        btnCrearComandaBar = new javax.swing.JButton();
        btnMarcarListaBar = new javax.swing.JButton();
        btnRefrescarBar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IblBienvenidaBar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IblBienvenidaBar.setText("Bar: Diego Campos ");

        btnCerrarSesionBar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesionBar.setText("Cerrar Sesion ");

        tblComandasBar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Número Comandas ", "Origen ", "Mesa ", "Hora Recibida", "Estado "
            }
        ));
        scrComandasBar.setViewportView(tblComandasBar);

        tblDetalleComandaBar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ítem", "Tipo", "Cantidad "
            }
        ));
        scrDetalleBar.setViewportView(tblDetalleComandaBar);

        btnVerDetalleBar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerDetalleBar.setText("Detalle Bar");

        btnCrearComandaBar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCrearComandaBar.setText("Crear Comanda");

        btnMarcarListaBar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMarcarListaBar.setText("Marcar Lista Bar");

        btnRefrescarBar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefrescarBar.setText("Refrescar Bar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerDetalleBar)
                .addGap(18, 18, 18)
                .addComponent(btnCrearComandaBar)
                .addGap(18, 18, 18)
                .addComponent(btnMarcarListaBar)
                .addGap(18, 18, 18)
                .addComponent(btnRefrescarBar)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrDetalleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(IblBienvenidaBar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCerrarSesionBar))
                        .addComponent(scrComandasBar, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSesionBar)
                    .addComponent(IblBienvenidaBar))
                .addGap(18, 18, 18)
                .addComponent(scrComandasBar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrDetalleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerDetalleBar)
                    .addComponent(btnCrearComandaBar)
                    .addComponent(btnMarcarListaBar)
                    .addComponent(btnRefrescarBar))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmBartender().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblBienvenidaBar;
    private javax.swing.JButton btnCerrarSesionBar;
    private javax.swing.JButton btnCrearComandaBar;
    private javax.swing.JButton btnMarcarListaBar;
    private javax.swing.JButton btnRefrescarBar;
    private javax.swing.JButton btnVerDetalleBar;
    private javax.swing.JScrollPane scrComandasBar;
    private javax.swing.JScrollPane scrDetalleBar;
    private javax.swing.JTable tblComandasBar;
    private javax.swing.JTable tblDetalleComandaBar;
    // End of variables declaration//GEN-END:variables
}
