/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import dao.ComandaDAO;
import dao.DetalleComandaDAO;
import dao.DetalleFacturaDAO;
import dao.FacturaDAO;
import dao.MesaDAO;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Comanda;
import model.DetalleComanda;
import model.DetalleFactura;
import model.Factura;
import model.Mesa;
import session.SesionActual;

/**
 * Pantalla de la caja: cobra las comandas, junta o separada, aplicando el IVA.
 *
 * @author valer
 */
public class FrmCajero extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCajero.class.getName());

    private final ComandaDAO comandaDAO = new ComandaDAO();
    private final DetalleComandaDAO detalleDAO = new DetalleComandaDAO();
    private final FacturaDAO facturaDAO = new FacturaDAO();
    private final DetalleFacturaDAO detalleFacturaDAO = new DetalleFacturaDAO();
    private final MesaDAO mesaDAO = new MesaDAO();

    private final DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    private List<Comanda> porCobrar = new ArrayList<>();       // comandas que faltan por facturar
    private List<DetalleComanda> detallesEnPantalla = new ArrayList<>(); // items sin facturar de la comanda escogida

    /**
     * Creates new form FrmCajero
     */
    public FrmCajero() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Restaurante - Caja");

        tblComandasPendientes.setDefaultEditor(Object.class, null);
        tblDetalleFactura.setDefaultEditor(Object.class, null);

        if (SesionActual.getUsuario() != null) {
            IblBienvenidaCaj.setText("Cajero: " + SesionActual.getNombre());
        }
        cargarPorCobrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IblBienvenidaCaj = new javax.swing.JLabel();
        btnCerrarSesionCaj = new javax.swing.JButton();
        scrComandasPendientes = new javax.swing.JScrollPane();
        tblComandasPendientes = new javax.swing.JTable();
        scrDetalleFacturaCaj = new javax.swing.JScrollPane();
        tblDetalleFactura = new javax.swing.JTable();
        chkCuentaSeparada = new javax.swing.JCheckBox();
        IblSubTotal = new javax.swing.JLabel();
        IblImpuesto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnVerDetalleCaj = new javax.swing.JButton();
        btnDividirCuenta = new javax.swing.JButton();
        btnGenerarFactura = new javax.swing.JButton();
        btnVerHistorialFacturas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IblBienvenidaCaj.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IblBienvenidaCaj.setText("Cajero: María López ");

        btnCerrarSesionCaj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesionCaj.setText("Cerrar Sesion ");
        btnCerrarSesionCaj.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnCerrarSesionCajActionPerformed(evt);
        });

        tblComandasPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número Comandas", "Origen", "Mesa ", "Empleado", "Total"
            }
        ));
        scrComandasPendientes.setViewportView(tblComandasPendientes);

        tblDetalleFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ítem ", "Cantidad", "Precio Unitario", "Precio Total "
            }
        ));
        scrDetalleFacturaCaj.setViewportView(tblDetalleFactura);

        chkCuentaSeparada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkCuentaSeparada.setText("Cuenta Separada?");

        IblSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblSubTotal.setText("SubTotal:");

        IblImpuesto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblImpuesto.setText("IVA:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Total:");

        btnVerDetalleCaj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerDetalleCaj.setText("Detalle Caja");
        btnVerDetalleCaj.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnVerDetalleCajActionPerformed(evt);
        });

        btnDividirCuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDividirCuenta.setText("Dividir Cuenta");
        btnDividirCuenta.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnDividirCuentaActionPerformed(evt);
        });

        btnGenerarFactura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerarFactura.setText("Generar Factura");
        btnGenerarFactura.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnGenerarFacturaActionPerformed(evt);
        });

        btnVerHistorialFacturas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerHistorialFacturas.setText("Historial Facturas");
        btnVerHistorialFacturas.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnVerHistorialFacturasActionPerformed(evt);
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrDetalleFacturaCaj)
                    .addComponent(scrComandasPendientes)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IblBienvenidaCaj, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesionCaj))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkCuentaSeparada, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IblImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnVerDetalleCaj)
                        .addGap(39, 39, 39)
                        .addComponent(btnDividirCuenta)
                        .addGap(36, 36, 36)
                        .addComponent(btnGenerarFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnVerHistorialFacturas)))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSesionCaj)
                    .addComponent(IblBienvenidaCaj))
                .addGap(18, 18, 18)
                .addComponent(scrComandasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrDetalleFacturaCaj, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCuentaSeparada)
                    .addComponent(IblSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IblImpuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerDetalleCaj)
                    .addComponent(btnDividirCuenta)
                    .addComponent(btnGenerarFactura)
                    .addComponent(btnVerHistorialFacturas))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionCajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionCajActionPerformed
        SesionActual.cerrarSesion();
        new FrmLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionCajActionPerformed

    private void btnVerDetalleCajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleCajActionPerformed
        verDetalle();
    }//GEN-LAST:event_btnVerDetalleCajActionPerformed

    private void btnGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFacturaActionPerformed
        // cuenta junta: se cobra todo lo que falta de la comanda
        if (chkCuentaSeparada.isSelected()) {
            JOptionPane.showMessageDialog(this,
                    "Tiene marcada la cuenta separada.\nUse el botón Dividir Cuenta con los ítems seleccionados.");
            return;
        }
        facturar(detallesEnPantalla, "toda la cuenta");
    }//GEN-LAST:event_btnGenerarFacturaActionPerformed

    private void btnDividirCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirCuentaActionPerformed
        dividirCuenta();
    }//GEN-LAST:event_btnDividirCuentaActionPerformed

    private void btnVerHistorialFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHistorialFacturasActionPerformed
        verHistorial();
    }//GEN-LAST:event_btnVerHistorialFacturasActionPerformed

    /** Trae las comandas que todavia tienen algo sin facturar. */
    private void cargarPorCobrar() {
        porCobrar = new ArrayList<>();
        List<Mesa> todasLasMesas = mesaDAO.findAll();

        DefaultTableModel modelo = (DefaultTableModel) tblComandasPendientes.getModel();
        modelo.setRowCount(0);

        for (Comanda c : comandaDAO.findAll()) {
            // solo se cobra lo que ya salió de cocina/bar o lo que el salonero cerró
            if (!"lista".equals(c.getEstado()) && !"cerrada".equals(c.getEstado())) {
                continue;
            }
            List<DetalleComanda> faltantes = detallesSinFacturar(c.getId_comanda());
            if (faltantes.isEmpty()) {
                continue; // esa comanda ya se cobró completa
            }
            porCobrar.add(c);
            modelo.addRow(new Object[]{
                c.getId_comanda(), c.getORIGEN(), nombreMesa(todasLasMesas, c.getId_mesa()),
                c.getCodigo_emp(), sumar(faltantes)
            });
        }

        limpiarDetalle();
    }

    /** Muestra los items que faltan por cobrar de la comanda escogida. */
    private void verDetalle() {
        int fila = tblComandasPendientes.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una comanda de la lista.");
            return;
        }

        detallesEnPantalla = detallesSinFacturar(porCobrar.get(fila).getId_comanda());

        DefaultTableModel modelo = (DefaultTableModel) tblDetalleFactura.getModel();
        modelo.setRowCount(0);
        for (DetalleComanda d : detallesEnPantalla) {
            modelo.addRow(new Object[]{
                detalleDAO.getNombreItem(d), d.getCantidad(), d.getPrecio_unit(), totalLinea(d)
            });
        }

        mostrarTotales(detallesEnPantalla);
    }

    /** Cobra solo los items marcados en la tabla (una persona de la mesa). */
    private void dividirCuenta() {
        if (!chkCuentaSeparada.isSelected()) {
            JOptionPane.showMessageDialog(this, "Marque primero la casilla \"Cuenta Separada?\".");
            return;
        }
        if (detallesEnPantalla.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero cargue el detalle de una comanda.");
            return;
        }

        int[] filas = tblDetalleFactura.getSelectedRows();
        if (filas.length == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione los ítems que va a pagar esta persona.");
            return;
        }

        List<DetalleComanda> deEstaPersona = new ArrayList<>();
        for (int fila : filas) {
            deEstaPersona.add(detallesEnPantalla.get(fila));
        }
        facturar(deEstaPersona, "los ítems seleccionados");
    }

    /** Crea la factura con los items que le pasen y le aplica el IVA. */
    private void facturar(List<DetalleComanda> items, String queSeCobra) {
        int fila = tblComandasPendientes.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una comanda de la lista.");
            return;
        }
        if (items.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero presione Detalle Caja para cargar los ítems.");
            return;
        }

        Comanda comanda = porCobrar.get(fila);
        BigDecimal subtotal = sumar(items);

        int respuesta = JOptionPane.showConfirmDialog(this,
                "Cobrar " + queSeCobra + " de la comanda #" + comanda.getId_comanda()
                + "\nSubtotal: ₡" + subtotal + "  |  Total con IVA: ₡" + conIva(subtotal),
                "Confirmar cobro", JOptionPane.YES_NO_OPTION);
        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }

        // si el salonero dejó una factura provisional, esa misma es la que se cancela aqui
        Factura factura = buscarProvisional(comanda.getId_comanda());
        boolean eraProvisional = factura != null;
        if (!eraProvisional) {
            factura = new Factura();
            factura.setId_comanda(comanda.getId_comanda());
        }
        factura.setCodigo_cajero(SesionActual.getCodigo());
        factura.setFecha_emision(LocalDateTime.now());
        factura.setSubtotal(subtotal);
        factura.setImpuesto(null); // en null para que el DAO los calcule con el 13%
        factura.setTotal(null);
        factura.setTipo("final");
        factura.setEstado("pagada");

        int idFactura;
        if (eraProvisional) {
            idFactura = facturaDAO.update(factura) ? factura.getId_factura() : -1;
        } else {
            idFactura = facturaDAO.insertGetId(factura);
        }
        if (idFactura <= 0) {
            JOptionPane.showMessageDialog(this, "No se pudo generar la factura.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // dejo apuntado cuales items entraron en esta factura
        for (DetalleComanda d : items) {
            DetalleFactura df = new DetalleFactura();
            df.setId_factura(idFactura);
            df.setId_detalle(d.getId_detalle());
            detalleFacturaDAO.insert(df);
        }

        // si ya no queda nada pendiente, la comanda se cierra y la mesa queda libre
        if (detallesSinFacturar(comanda.getId_comanda()).isEmpty()) {
            comandaDAO.updateEstado(comanda.getId_comanda(), "cerrada");
            liberarMesa(comanda.getId_mesa());
        }

        JOptionPane.showMessageDialog(this,
                "Factura #" + idFactura + " generada.\nSubtotal: ₡" + factura.getSubtotal()
                + "\nIVA (13%): ₡" + factura.getImpuesto() + "\nTotal: ₡" + factura.getTotal());

        cargarPorCobrar();
    }

    /** Muestra en un cuadro las facturas que se han emitido. */
    private void verHistorial() {
        List<Factura> facturas = facturaDAO.findAll();
        if (facturas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todavía no hay facturas emitidas.");
            return;
        }

        String texto = "Facturas emitidas:\n\n";
        BigDecimal granTotal = BigDecimal.ZERO;
        int provisionales = 0;
        for (Factura f : facturas) {
            String fecha = f.getFecha_emision() != null ? f.getFecha_emision().format(formatoHora) : "";
            texto += "#" + f.getId_factura() + "  comanda " + f.getId_comanda() + "  " + fecha
                    + "  ₡" + f.getTotal() + "  (" + f.getTipo() + " / " + f.getEstado() + ")\n";
            // solo sumo las finales; las provisionales todavia no se han cobrado
            if ("final".equals(f.getTipo()) && f.getTotal() != null) {
                granTotal = granTotal.add(f.getTotal());
            } else {
                provisionales++;
            }
        }
        texto += "\nTotal cobrado (facturas finales): ₡" + granTotal;
        if (provisionales > 0) {
            texto += "\nProvisionales pendientes de cobro: " + provisionales;
        }

        JOptionPane.showMessageDialog(this, texto, "Historial de facturas", JOptionPane.INFORMATION_MESSAGE);
    }

    // ------------------ ayudas ------------------

    /** Busca la factura provisional de una comanda, si el salonero la dejó. */
    private Factura buscarProvisional(int idComanda) {
        for (Factura f : facturaDAO.findByComanda(idComanda)) {
            if ("provisional".equals(f.getTipo())) {
                return f;
            }
        }
        return null;
    }

    /** Devuelve los detalles de la comanda que todavia no estan en ninguna factura final. */
    private List<DetalleComanda> detallesSinFacturar(int idComanda) {
        // junto los detalles que ya se cobraron. La provisional que saca el salonero
        // no cuenta, porque esa todavia no se ha cancelado en caja.
        List<Integer> yaCobrados = new ArrayList<>();
        for (Factura f : facturaDAO.findByComanda(idComanda)) {
            if (!"final".equals(f.getTipo())) {
                continue;
            }
            for (DetalleFactura df : detalleFacturaDAO.findByFactura(f.getId_factura())) {
                yaCobrados.add(df.getId_detalle());
            }
        }

        List<DetalleComanda> faltantes = new ArrayList<>();
        for (DetalleComanda d : detalleDAO.findByComanda(idComanda)) {
            if (!yaCobrados.contains(d.getId_detalle())) {
                faltantes.add(d);
            }
        }
        return faltantes;
    }

    /** Pone el subtotal, el IVA y el total en las etiquetas. */
    private void mostrarTotales(List<DetalleComanda> items) {
        BigDecimal subtotal = sumar(items);
        BigDecimal iva = subtotal.multiply(FacturaDAO.IVA).setScale(2, java.math.RoundingMode.HALF_UP);
        IblSubTotal.setText("SubTotal: ₡" + subtotal);
        IblImpuesto.setText("IVA (13%): ₡" + iva);
        jLabel3.setText("Total: ₡" + subtotal.add(iva));
    }

    /** Suma el precio de todos los items. */
    private BigDecimal sumar(List<DetalleComanda> items) {
        BigDecimal suma = BigDecimal.ZERO;
        for (DetalleComanda d : items) {
            suma = suma.add(totalLinea(d));
        }
        return suma;
    }

    /** Precio de una linea = precio unitario por cantidad. */
    private BigDecimal totalLinea(DetalleComanda detalle) {
        if (detalle.getPrecio_unit() == null) {
            return BigDecimal.ZERO;
        }
        return detalle.getPrecio_unit().multiply(new BigDecimal(detalle.getCantidad()));
    }

    /** Le suma el 13% al subtotal. */
    private BigDecimal conIva(BigDecimal subtotal) {
        return subtotal.add(subtotal.multiply(FacturaDAO.IVA).setScale(2, java.math.RoundingMode.HALF_UP));
    }

    /** Deja la mesa disponible otra vez. */
    private void liberarMesa(int idMesa) {
        for (Mesa m : mesaDAO.findAll()) {
            if (m.getId_mesa() == idMesa) {
                m.setDisponible(1);
                mesaDAO.update(m);
            }
        }
    }

    /** Busca el número de mesa, para no mostrar el id pelado. */
    private String nombreMesa(List<Mesa> lista, int idMesa) {
        for (Mesa m : lista) {
            if (m.getId_mesa() == idMesa) {
                return "Mesa " + m.getNumero_mesa();
            }
        }
        return "-";
    }

    /** Deja el detalle y los totales en blanco. */
    private void limpiarDetalle() {
        detallesEnPantalla = new ArrayList<>();
        ((DefaultTableModel) tblDetalleFactura.getModel()).setRowCount(0);
        IblSubTotal.setText("SubTotal:");
        IblImpuesto.setText("IVA:");
        jLabel3.setText("Total:");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCajero().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblBienvenidaCaj;
    private javax.swing.JLabel IblImpuesto;
    private javax.swing.JLabel IblSubTotal;
    private javax.swing.JButton btnCerrarSesionCaj;
    private javax.swing.JButton btnDividirCuenta;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JButton btnVerDetalleCaj;
    private javax.swing.JButton btnVerHistorialFacturas;
    private javax.swing.JCheckBox chkCuentaSeparada;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane scrComandasPendientes;
    private javax.swing.JScrollPane scrDetalleFacturaCaj;
    private javax.swing.JTable tblComandasPendientes;
    private javax.swing.JTable tblDetalleFactura;
    // End of variables declaration//GEN-END:variables
}
