/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import dao.ComandaDAO;
import dao.DetalleComandaDAO;
import dao.DetalleFacturaDAO;
import dao.FacturaDAO;
import dao.MesaDAO;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Comanda;
import model.DetalleComanda;
import model.DetalleFactura;
import model.Factura;
import model.Mesa;
import session.SesionActual;

/**
 * Cashier screen: it charges the orders, together or split, applying the sales tax.
 *
 * @author valer
 */
public class FrmCajero extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCajero.class.getName());

    private final ComandaDAO comandaDAO = new ComandaDAO();
    private final DetalleComandaDAO detalleDAO = new DetalleComandaDAO();
    private final FacturaDAO facturaDAO = new FacturaDAO();
    private final DetalleFacturaDAO detalleFacturaDAO = new DetalleFacturaDAO();
    private final MesaDAO mesaDAO = new MesaDAO();

    private final DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    // shorter date, so the history columns fit on the paper
    private final DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yy HH:mm");

    private List<Comanda> porCobrar = new ArrayList<>();       // orders that still have something to charge
    private List<DetalleComanda> detallesEnPantalla = new ArrayList<>(); // unpaid items of the selected order

    /**
     * Creates new form FrmCajero
     */
    public FrmCajero() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Restaurante - Caja");

        tblComandasPendientes.setDefaultEditor(Object.class, null);
        tblDetalleFactura.setDefaultEditor(Object.class, null);

        if (SesionActual.getUsuario() != null) {
            IblBienvenidaCaj.setText("Cajero: " + SesionActual.getNombre());
        }
        cargarPorCobrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IblBienvenidaCaj = new javax.swing.JLabel();
        btnCerrarSesionCaj = new javax.swing.JButton();
        scrComandasPendientes = new javax.swing.JScrollPane();
        tblComandasPendientes = new javax.swing.JTable();
        scrDetalleFacturaCaj = new javax.swing.JScrollPane();
        tblDetalleFactura = new javax.swing.JTable();
        chkCuentaSeparada = new javax.swing.JCheckBox();
        IblSubTotal = new javax.swing.JLabel();
        IblImpuesto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnVerDetalleCaj = new javax.swing.JButton();
        btnDividirCuenta = new javax.swing.JButton();
        btnGenerarFactura = new javax.swing.JButton();
        btnVerHistorialFacturas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IblBienvenidaCaj.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IblBienvenidaCaj.setText("Cajero: María López ");

        btnCerrarSesionCaj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesionCaj.setText("Cerrar Sesion ");
        btnCerrarSesionCaj.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnCerrarSesionCajActionPerformed(evt);
        });

        tblComandasPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número Comandas", "Origen", "Mesa ", "Empleado", "Total"
            }
        ));
        scrComandasPendientes.setViewportView(tblComandasPendientes);

        tblDetalleFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ítem ", "Cantidad", "Precio Unitario", "Precio Total "
            }
        ));
        scrDetalleFacturaCaj.setViewportView(tblDetalleFactura);

        chkCuentaSeparada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkCuentaSeparada.setText("Cuenta Separada?");

        IblSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblSubTotal.setText("SubTotal:");

        IblImpuesto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblImpuesto.setText("IVA:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Total:");

        btnVerDetalleCaj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerDetalleCaj.setText("Detalle Caja");
        btnVerDetalleCaj.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnVerDetalleCajActionPerformed(evt);
        });

        btnDividirCuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDividirCuenta.setText("Dividir Cuenta");
        btnDividirCuenta.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnDividirCuentaActionPerformed(evt);
        });

        btnGenerarFactura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerarFactura.setText("Generar Factura");
        btnGenerarFactura.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnGenerarFacturaActionPerformed(evt);
        });

        btnVerHistorialFacturas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerHistorialFacturas.setText("Historial Facturas");
        btnVerHistorialFacturas.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnVerHistorialFacturasActionPerformed(evt);
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrDetalleFacturaCaj)
                    .addComponent(scrComandasPendientes)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IblBienvenidaCaj, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesionCaj))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkCuentaSeparada, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IblImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnVerDetalleCaj)
                        .addGap(39, 39, 39)
                        .addComponent(btnDividirCuenta)
                        .addGap(36, 36, 36)
                        .addComponent(btnGenerarFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnVerHistorialFacturas)))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSesionCaj)
                    .addComponent(IblBienvenidaCaj))
                .addGap(18, 18, 18)
                .addComponent(scrComandasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrDetalleFacturaCaj, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCuentaSeparada)
                    .addComponent(IblSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IblImpuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerDetalleCaj)
                    .addComponent(btnDividirCuenta)
                    .addComponent(btnGenerarFactura)
                    .addComponent(btnVerHistorialFacturas))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionCajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionCajActionPerformed
        SesionActual.cerrarSesion();
        new FrmLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionCajActionPerformed

    private void btnVerDetalleCajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleCajActionPerformed
        verDetalle();
    }//GEN-LAST:event_btnVerDetalleCajActionPerformed

    private void btnGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFacturaActionPerformed
        // single bill: everything left on the order is charged at once
        if (chkCuentaSeparada.isSelected()) {
            JOptionPane.showMessageDialog(this,
                    "Tiene marcada la cuenta separada.\nUse el botón Dividir Cuenta con los ítems seleccionados.");
            return;
        }
        facturar(detallesEnPantalla, "toda la cuenta");
    }//GEN-LAST:event_btnGenerarFacturaActionPerformed

    private void btnDividirCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirCuentaActionPerformed
        dividirCuenta();
    }//GEN-LAST:event_btnDividirCuentaActionPerformed

    private void btnVerHistorialFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHistorialFacturasActionPerformed
        verHistorial();
    }//GEN-LAST:event_btnVerHistorialFacturasActionPerformed

    /** Loads the orders that still have something left to charge. */
    private void cargarPorCobrar() {
        porCobrar = new ArrayList<>();
        List<Mesa> todasLasMesas = mesaDAO.findAll();

        DefaultTableModel modelo = (DefaultTableModel) tblComandasPendientes.getModel();
        modelo.setRowCount(0);

        for (Comanda c : comandaDAO.findAll()) {
            // only what already left the kitchen or the bar, or what the waiter closed, can be charged
            if (!"lista".equals(c.getEstado()) && !"cerrada".equals(c.getEstado())) {
                continue;
            }
            List<DetalleComanda> faltantes = detallesSinFacturar(c.getId_comanda());
            if (faltantes.isEmpty()) {
                continue; // that order was fully charged already
            }
            porCobrar.add(c);
            modelo.addRow(new Object[]{
                c.getId_comanda(), c.getORIGEN(), nombreMesa(todasLasMesas, c.getId_mesa()),
                c.getCodigo_emp(), sumar(faltantes)
            });
        }

        limpiarDetalle();
    }

    /** Shows the items left to charge on the selected order. */
    private void verDetalle() {
        int fila = tblComandasPendientes.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una comanda de la lista.");
            return;
        }

        detallesEnPantalla = detallesSinFacturar(porCobrar.get(fila).getId_comanda());

        DefaultTableModel modelo = (DefaultTableModel) tblDetalleFactura.getModel();
        modelo.setRowCount(0);
        for (DetalleComanda d : detallesEnPantalla) {
            modelo.addRow(new Object[]{
                detalleDAO.getNombreItem(d), d.getCantidad(), d.getPrecio_unit(), totalLinea(d)
            });
        }

        mostrarTotales(detallesEnPantalla);
    }

    /** Charges only the items selected in the table, that is, one person of the party. */
    private void dividirCuenta() {
        if (!chkCuentaSeparada.isSelected()) {
            JOptionPane.showMessageDialog(this, "Marque primero la casilla \"Cuenta Separada?\".");
            return;
        }
        if (detallesEnPantalla.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero cargue el detalle de una comanda.");
            return;
        }

        int[] filas = tblDetalleFactura.getSelectedRows();
        if (filas.length == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione los ítems que va a pagar esta persona.");
            return;
        }

        List<DetalleComanda> deEstaPersona = new ArrayList<>();
        for (int fila : filas) {
            deEstaPersona.add(detallesEnPantalla.get(fila));
        }
        facturar(deEstaPersona, "los ítems seleccionados");
    }

    /** Creates the invoice with the given items and applies the sales tax. */
    private void facturar(List<DetalleComanda> items, String queSeCobra) {
        int fila = tblComandasPendientes.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una comanda de la lista.");
            return;
        }
        if (items.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero presione Detalle Caja para cargar los ítems.");
            return;
        }

        Comanda comanda = porCobrar.get(fila);
        BigDecimal subtotal = sumar(items);

        int respuesta = JOptionPane.showConfirmDialog(this,
                "Cobrar " + queSeCobra + " de la comanda #" + comanda.getId_comanda()
                + "\nSubtotal: ₡" + subtotal + "  |  Total con IVA: ₡" + conIva(subtotal),
                "Confirmar cobro", JOptionPane.YES_NO_OPTION);
        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }

        // when the waiter left a provisional invoice, that same one is settled here
        Factura factura = buscarProvisional(comanda.getId_comanda());
        boolean eraProvisional = factura != null;
        if (!eraProvisional) {
            factura = new Factura();
            factura.setId_comanda(comanda.getId_comanda());
        }
        factura.setCodigo_cajero(SesionActual.getCodigo());
        factura.setFecha_emision(LocalDateTime.now());
        factura.setSubtotal(subtotal);
        factura.setImpuesto(null); // left null so the DAO computes them with the 13 percent
        factura.setTotal(null);
        factura.setTipo("final");
        factura.setEstado("pagada");

        int idFactura;
        if (eraProvisional) {
            idFactura = facturaDAO.update(factura) ? factura.getId_factura() : -1;
        } else {
            idFactura = facturaDAO.insertGetId(factura);
        }
        if (idFactura <= 0) {
            JOptionPane.showMessageDialog(this, "No se pudo generar la factura.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // keep track of which items went into this invoice
        for (DetalleComanda d : items) {
            DetalleFactura df = new DetalleFactura();
            df.setId_factura(idFactura);
            df.setId_detalle(d.getId_detalle());
            detalleFacturaDAO.insert(df);
        }

        // when nothing is left the order is closed and the table is freed
        if (detallesSinFacturar(comanda.getId_comanda()).isEmpty()) {
            comandaDAO.updateEstado(comanda.getId_comanda(), "cerrada");
            liberarMesa(comanda.getId_mesa());
        }

        // the receipt the customer takes: same items that were just charged
        String lineas = "";
        for (DetalleComanda d : items) {
            lineas = lineas + Tiquete.item(d.getCantidad(), detalleDAO.getNombreItem(d),
                    d.getPrecio_unit().multiply(new BigDecimal(d.getCantidad())));
        }

        String tiquete = Tiquete.cabecera("FACTURA", "No. " + idFactura)
                + Tiquete.dato("Fecha", factura.getFecha_emision().format(formatoHora))
                + Tiquete.dato("Comanda", "#" + comanda.getId_comanda())
                + Tiquete.dato("Cajero", SesionActual.getNombre())
                + Tiquete.dato("Cuenta", queSeCobra)
                + Tiquete.titulosItems()
                + lineas
                + Tiquete.separador()
                + Tiquete.total("Subtotal", factura.getSubtotal())
                + Tiquete.total("IVA (13%)", factura.getImpuesto())
                + Tiquete.total("TOTAL PAGADO", factura.getTotal())
                + Tiquete.pie("Gracias por su visita");

        Tiquete.mostrar(this, "Factura " + idFactura, tiquete);

        cargarPorCobrar();
    }

    /** Shows the invoices already issued in a dialog. */
    private void verHistorial() {
        List<Factura> facturas = facturaDAO.findAll();
        if (facturas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todavía no hay facturas emitidas.");
            return;
        }

        String lineas = "";
        BigDecimal granTotal = BigDecimal.ZERO;
        int provisionales = 0;
        for (Factura f : facturas) {
            String fecha = f.getFecha_emision() != null ? f.getFecha_emision().format(formatoCorto) : "";
            // only the final ones are added up; the provisional ones have not been paid yet
            boolean cobrada = "final".equals(f.getTipo()) && f.getTotal() != null;
            if (cobrada) {
                granTotal = granTotal.add(f.getTotal());
            } else {
                provisionales++;
            }
            lineas = lineas + Tiquete.lineaHistorial(f.getId_factura(), f.getId_comanda(), fecha,
                    f.getTotal(), cobrada ? "pagada" : "provisional");
        }

        String tiquete = Tiquete.cabeceraLista("HISTORIAL DE FACTURAS")
                + Tiquete.titulosHistorial()
                + lineas
                + Tiquete.separadorLista()
                + Tiquete.totalLista("Total cobrado", granTotal);
        if (provisionales == 1) {
            tiquete = tiquete + Tiquete.pieLista("1 provisional sin cobrar");
        } else if (provisionales > 1) {
            tiquete = tiquete + Tiquete.pieLista(provisionales + " provisionales sin cobrar");
        } else {
            tiquete = tiquete + Tiquete.pieLista("No quedan facturas pendientes");
        }

        Tiquete.mostrar(this, "Historial de facturas", tiquete);
    }

    // ------------------ helpers ------------------

    /** Finds the provisional invoice of an order, when the waiter issued one. */
    private Factura buscarProvisional(int idComanda) {
        for (Factura f : facturaDAO.findByComanda(idComanda)) {
            if ("provisional".equals(f.getTipo())) {
                return f;
            }
        }
        return null;
    }

    /** Returns the order details that are not part of any final invoice yet. */
    private List<DetalleComanda> detallesSinFacturar(int idComanda) {
        // collect the details already charged. The provisional invoice issued by the waiter
        // does not count, because it has not been paid at the cashier yet.
        List<Integer> yaCobrados = new ArrayList<>();
        for (Factura f : facturaDAO.findByComanda(idComanda)) {
            if (!"final".equals(f.getTipo())) {
                continue;
            }
            for (DetalleFactura df : detalleFacturaDAO.findByFactura(f.getId_factura())) {
                yaCobrados.add(df.getId_detalle());
            }
        }

        List<DetalleComanda> faltantes = new ArrayList<>();
        for (DetalleComanda d : detalleDAO.findByComanda(idComanda)) {
            if (!yaCobrados.contains(d.getId_detalle())) {
                faltantes.add(d);
            }
        }
        return faltantes;
    }

    /** Writes the subtotal, the sales tax and the total into the labels. */
    private void mostrarTotales(List<DetalleComanda> items) {
        BigDecimal subtotal = sumar(items);
        BigDecimal iva = subtotal.multiply(FacturaDAO.IVA).setScale(2, java.math.RoundingMode.HALF_UP);
        IblSubTotal.setText("SubTotal: ₡" + subtotal);
        IblImpuesto.setText("IVA (13%): ₡" + iva);
        jLabel3.setText("Total: ₡" + subtotal.add(iva));
    }

    /** Adds up the price of every item. */
    private BigDecimal sumar(List<DetalleComanda> items) {
        BigDecimal suma = BigDecimal.ZERO;
        for (DetalleComanda d : items) {
            suma = suma.add(totalLinea(d));
        }
        return suma;
    }

    /** Price of one line, that is, unit price times quantity. */
    private BigDecimal totalLinea(DetalleComanda detalle) {
        if (detalle.getPrecio_unit() == null) {
            return BigDecimal.ZERO;
        }
        return detalle.getPrecio_unit().multiply(new BigDecimal(detalle.getCantidad()));
    }

    /** Adds the 13 percent tax to the subtotal. */
    private BigDecimal conIva(BigDecimal subtotal) {
        return subtotal.add(subtotal.multiply(FacturaDAO.IVA).setScale(2, java.math.RoundingMode.HALF_UP));
    }

    /** Makes the table available again. */
    private void liberarMesa(int idMesa) {
        for (Mesa m : mesaDAO.findAll()) {
            if (m.getId_mesa() == idMesa) {
                m.setDisponible(1);
                mesaDAO.update(m);
            }
        }
    }

    /** Finds the table number, so the raw id is not displayed. */
    private String nombreMesa(List<Mesa> lista, int idMesa) {
        for (Mesa m : lista) {
            if (m.getId_mesa() == idMesa) {
                return "Mesa " + m.getNumero_mesa();
            }
        }
        return "-";
    }

    /** Clears the detail table and the totals. */
    private void limpiarDetalle() {
        detallesEnPantalla = new ArrayList<>();
        ((DefaultTableModel) tblDetalleFactura.getModel()).setRowCount(0);
        IblSubTotal.setText("SubTotal:");
        IblImpuesto.setText("IVA:");
        jLabel3.setText("Total:");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCajero().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblBienvenidaCaj;
    private javax.swing.JLabel IblImpuesto;
    private javax.swing.JLabel IblSubTotal;
    private javax.swing.JButton btnCerrarSesionCaj;
    private javax.swing.JButton btnDividirCuenta;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JButton btnVerDetalleCaj;
    private javax.swing.JButton btnVerHistorialFacturas;
    private javax.swing.JCheckBox chkCuentaSeparada;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane scrComandasPendientes;
    private javax.swing.JScrollPane scrDetalleFacturaCaj;
    private javax.swing.JTable tblComandasPendientes;
    private javax.swing.JTable tblDetalleFactura;
    // End of variables declaration//GEN-END:variables
}
