/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import dao.ComandaDAO;
import dao.DetalleComandaDAO;
import dao.MesaDAO;
import dao.ProcesoBarDAO;
import dao.ProcesoCocinaDAO;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Comanda;
import model.DetalleComanda;
import model.Mesa;
import model.ProcesoBar;
import model.ProcesoCocina;
import session.SesionActual;

/**
 * Kitchen screen: it shows the pending orders and marks them as ready.
 *
 * @author valer
 */
public class FrmCocinero extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCocinero.class.getName());

    // an order has 20 minutes to be served
    private static final int LIMITE_MINUTOS = 20;

    private final ProcesoCocinaDAO cocinaDAO = new ProcesoCocinaDAO();
    private final ProcesoBarDAO barDAO = new ProcesoBarDAO();
    private final ComandaDAO comandaDAO = new ComandaDAO();
    private final DetalleComandaDAO detalleDAO = new DetalleComandaDAO();
    private final MesaDAO mesaDAO = new MesaDAO();

    private final DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    private List<ProcesoCocina> pendientes = new ArrayList<>();

    /**
     * Creates new form FrmCocinero
     */
    public FrmCocinero() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Restaurante - Cocina");

        tblComandasCocina.setDefaultEditor(Object.class, null);
        tblDetalleComandaCocina.setDefaultEditor(Object.class, null);

        if (SesionActual.getUsuario() != null) {
            IblBienvenidaCos.setText("Cocina: " + SesionActual.getNombre());
        }
        cargarPendientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IblBienvenidaCos = new javax.swing.JLabel();
        btnCerrarSesionCos = new javax.swing.JButton();
        scrComandasCocina = new javax.swing.JScrollPane();
        tblComandasCocina = new javax.swing.JTable();
        scrDetalleCocina = new javax.swing.JScrollPane();
        tblDetalleComandaCocina = new javax.swing.JTable();
        btnVerDetalleCocina = new javax.swing.JButton();
        btnMarcarListaCocina = new javax.swing.JButton();
        btnRefrescarCocina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IblBienvenidaCos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IblBienvenidaCos.setText("Cocina: Pedro Rojas");

        btnCerrarSesionCos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesionCos.setText("Cerrar Sesion ");
        btnCerrarSesionCos.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnCerrarSesionCosActionPerformed(evt);
        });

        tblComandasCocina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número Comandas ", "Origen ", "Mesa", "Hora Recibida ", "Estado"
            }
        ));
        scrComandasCocina.setViewportView(tblComandasCocina);

        tblDetalleComandaCocina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plato", "Cantidad"
            }
        ));
        scrDetalleCocina.setViewportView(tblDetalleComandaCocina);

        btnVerDetalleCocina.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerDetalleCocina.setText("Detalle Comanda");
        btnVerDetalleCocina.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnVerDetalleCocinaActionPerformed(evt);
        });

        btnMarcarListaCocina.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMarcarListaCocina.setText("Proceso Cocina ");
        btnMarcarListaCocina.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnMarcarListaCocinaActionPerformed(evt);
        });

        btnRefrescarCocina.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefrescarCocina.setText("Refrescar Cocina ");
        btnRefrescarCocina.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnRefrescarCocinaActionPerformed(evt);
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IblBienvenidaCos)
                                .addGap(300, 300, 300)
                                .addComponent(btnCerrarSesionCos))
                            .addComponent(scrComandasCocina)
                            .addComponent(scrDetalleCocina)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnVerDetalleCocina)
                        .addGap(53, 53, 53)
                        .addComponent(btnMarcarListaCocina)
                        .addGap(50, 50, 50)
                        .addComponent(btnRefrescarCocina)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblBienvenidaCos)
                    .addComponent(btnCerrarSesionCos))
                .addGap(38, 38, 38)
                .addComponent(scrComandasCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrDetalleCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerDetalleCocina)
                    .addComponent(btnMarcarListaCocina)
                    .addComponent(btnRefrescarCocina))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionCosActionPerformed
        SesionActual.cerrarSesion();
        new FrmLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionCosActionPerformed

    private void btnRefrescarCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarCocinaActionPerformed
        cargarPendientes();
    }//GEN-LAST:event_btnRefrescarCocinaActionPerformed

    private void btnVerDetalleCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleCocinaActionPerformed
        verDetalle();
    }//GEN-LAST:event_btnVerDetalleCocinaActionPerformed

    private void btnMarcarListaCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarListaCocinaActionPerformed
        marcarLista();
    }//GEN-LAST:event_btnMarcarListaCocinaActionPerformed

    /** Loads the orders the kitchen has not finished yet. */
    private void cargarPendientes() {
        pendientes = cocinaDAO.findPendientes();
        List<Mesa> todasLasMesas = mesaDAO.findAll();

        DefaultTableModel modelo = (DefaultTableModel) tblComandasCocina.getModel();
        modelo.setRowCount(0);

        for (ProcesoCocina p : pendientes) {
            Comanda c = comandaDAO.findById(p.getId_comanda());
            if (c == null) {
                continue;
            }
            String hora = p.getHora_recibida() != null ? p.getHora_recibida().format(formatoHora) : "";
            // when it went over the 20 minutes it is flagged in the table itself
            String estado = c.getEstado();
            if (minutosEsperando(p) > LIMITE_MINUTOS) {
                estado = estado + " (atrasada)";
            }
            modelo.addRow(new Object[]{c.getId_comanda(), c.getORIGEN(), nombreMesa(todasLasMesas, c.getId_mesa()), hora, estado});
        }

        limpiarDetalle();
    }

    /** Shows only the dishes of the selected order; the drinks belong to the bar. */
    private void verDetalle() {
        int fila = tblComandasCocina.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una comanda de la lista.");
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tblDetalleComandaCocina.getModel();
        modelo.setRowCount(0);

        List<DetalleComanda> detalles = detalleDAO.findByComanda(pendientes.get(fila).getId_comanda());
        for (DetalleComanda d : detalles) {
            if ("comida".equals(d.getTipo_item())) {
                modelo.addRow(new Object[]{detalleDAO.getNombreItem(d), d.getCantidad()});
            }
        }

        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Esa comanda no tiene platos, solo bebidas.");
        }
    }

    /** Marks the order as ready in the kitchen and notifies the waiter. */
    private void marcarLista() {
        int fila = tblComandasCocina.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una comanda de la lista.");
            return;
        }

        ProcesoCocina proceso = pendientes.get(fila);
        proceso.setHora_lista(LocalDateTime.now());
        proceso.setCodigo_cos(SesionActual.getCodigo());

        if (!cocinaDAO.update(proceso)) {
            JOptionPane.showMessageDialog(this, "No se pudo marcar la comanda.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // the order becomes ready only when the bar finished its part too
        ProcesoBar procesoBar = barDAO.findByComanda(proceso.getId_comanda());
        if (procesoBar == null || procesoBar.getHora_lista() != null) {
            comandaDAO.updateEstado(proceso.getId_comanda(), "lista");
            JOptionPane.showMessageDialog(this, "Comanda #" + proceso.getId_comanda() + " lista para servir.");
        } else {
            comandaDAO.updateEstado(proceso.getId_comanda(), "en_proceso");
            JOptionPane.showMessageDialog(this, "Platos listos. Falta que el bar termine las bebidas.");
        }

        cargarPendientes();
    }

    /** Empties the detail table. */
    private void limpiarDetalle() {
        ((DefaultTableModel) tblDetalleComandaCocina.getModel()).setRowCount(0);
    }

    /** Minutes the order has been waiting in the kitchen. */
    private long minutosEsperando(ProcesoCocina proceso) {
        if (proceso.getHora_recibida() == null) {
            return 0;
        }
        return Duration.between(proceso.getHora_recibida(), LocalDateTime.now()).toMinutes();
    }

    /** Finds the table number, so the raw id is not displayed. */
    private String nombreMesa(List<Mesa> lista, int idMesa) {
        for (Mesa m : lista) {
            if (m.getId_mesa() == idMesa) {
                return "Mesa " + m.getNumero_mesa();
            }
        }
        return "-";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCocinero().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblBienvenidaCos;
    private javax.swing.JButton btnCerrarSesionCos;
    private javax.swing.JButton btnMarcarListaCocina;
    private javax.swing.JButton btnRefrescarCocina;
    private javax.swing.JButton btnVerDetalleCocina;
    private javax.swing.JScrollPane scrComandasCocina;
    private javax.swing.JScrollPane scrDetalleCocina;
    private javax.swing.JTable tblComandasCocina;
    private javax.swing.JTable tblDetalleComandaCocina;
    // End of variables declaration//GEN-END:variables
}
