/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author valer
 */
public class FrmCajero extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCajero.class.getName());

    /**
     * Creates new form FrmCajero
     */
    public FrmCajero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IblBienvenidaCaj = new javax.swing.JLabel();
        btnCerrarSesionCaj = new javax.swing.JButton();
        scrComandasPendientes = new javax.swing.JScrollPane();
        tblComandasPendientes = new javax.swing.JTable();
        scrDetalleFacturaCaj = new javax.swing.JScrollPane();
        tblDetalleFactura = new javax.swing.JTable();
        chkCuentaSeparada = new javax.swing.JCheckBox();
        IblSubTotal = new javax.swing.JLabel();
        IblImpuesto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnVerDetalleCaj = new javax.swing.JButton();
        btnDividirCuenta = new javax.swing.JButton();
        btnGenerarFactura = new javax.swing.JButton();
        btnVerHistorialFacturas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IblBienvenidaCaj.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IblBienvenidaCaj.setText("Cajero: María López ");

        btnCerrarSesionCaj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesionCaj.setText("Cerrar Sesion ");

        tblComandasPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Número Comandas", "Origen", "Mesa ", "Empleado", "Total"
            }
        ));
        scrComandasPendientes.setViewportView(tblComandasPendientes);

        tblDetalleFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ítem ", "Cantidad", "Precio Unitario", "Precio Total "
            }
        ));
        scrDetalleFacturaCaj.setViewportView(tblDetalleFactura);

        chkCuentaSeparada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkCuentaSeparada.setText("Cuenta Separada?");

        IblSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblSubTotal.setText("SubTotal:");

        IblImpuesto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblImpuesto.setText("IVA:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Total:");

        btnVerDetalleCaj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerDetalleCaj.setText("Detalle Caja");

        btnDividirCuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDividirCuenta.setText("Dividir Cuenta");

        btnGenerarFactura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerarFactura.setText("Generar Factura");

        btnVerHistorialFacturas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerHistorialFacturas.setText("Historial Facturas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrDetalleFacturaCaj)
                    .addComponent(scrComandasPendientes)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IblBienvenidaCaj, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesionCaj))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkCuentaSeparada, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IblImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnVerDetalleCaj)
                        .addGap(39, 39, 39)
                        .addComponent(btnDividirCuenta)
                        .addGap(36, 36, 36)
                        .addComponent(btnGenerarFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnVerHistorialFacturas)))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSesionCaj)
                    .addComponent(IblBienvenidaCaj))
                .addGap(18, 18, 18)
                .addComponent(scrComandasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrDetalleFacturaCaj, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCuentaSeparada)
                    .addComponent(IblSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IblImpuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerDetalleCaj)
                    .addComponent(btnDividirCuenta)
                    .addComponent(btnGenerarFactura)
                    .addComponent(btnVerHistorialFacturas))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCajero().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblBienvenidaCaj;
    private javax.swing.JLabel IblImpuesto;
    private javax.swing.JLabel IblSubTotal;
    private javax.swing.JButton btnCerrarSesionCaj;
    private javax.swing.JButton btnDividirCuenta;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JButton btnVerDetalleCaj;
    private javax.swing.JButton btnVerHistorialFacturas;
    private javax.swing.JCheckBox chkCuentaSeparada;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane scrComandasPendientes;
    private javax.swing.JScrollPane scrDetalleFacturaCaj;
    private javax.swing.JTable tblComandasPendientes;
    private javax.swing.JTable tblDetalleFactura;
    // End of variables declaration//GEN-END:variables
}
