/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import session.SesionActual;

/**
 * Login window. It opens the screen that matches the role of the user.
 *
 * @author valer
 */
public class FrmLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        setLocationRelativeTo(null); // center the window
        IblMensaje.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipo = new javax.swing.ButtonGroup();
        IblTitulo = new javax.swing.JLabel();
        IblLogo = new javax.swing.JLabel();
        rbEmpleado = new javax.swing.JRadioButton();
        rbAdmin = new javax.swing.JRadioButton();
        IblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        IblContrasena = new javax.swing.JLabel();
        pwdContrasena = new javax.swing.JPasswordField();
        IblMensaje = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante - Login");
        setResizable(false);

        IblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IblTitulo.setText("Restaurante - Inicio de Sesión");

        grupoTipo.add(rbEmpleado);
        rbEmpleado.setSelected(true);
        rbEmpleado.setText("Empleado");

        grupoTipo.add(rbAdmin);
        rbAdmin.setText("Administrador");

        IblUsuario.setText("Código / Usuario:");

        IblContrasena.setText("Contraseña:");

        pwdContrasena.addActionListener((java.awt.event.ActionEvent evt) -> {
            pwdContrasenaActionPerformed(evt);
        });

        IblMensaje.setForeground(new java.awt.Color(255, 51, 51));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnIngresarActionPerformed(evt);
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnSalirActionPerformed(evt);
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(IblTitulo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(174, 174, 174)
                            .addComponent(IblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(rbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rbAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(IblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IblUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IblContrasena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwdContrasena, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(IblLogo)
                .addGap(18, 18, 18)
                .addComponent(IblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEmpleado)
                    .addComponent(rbAdmin))
                .addGap(18, 18, 18)
                .addComponent(IblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IblContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IblMensaje)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnSalir))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        ingresar();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void pwdContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdContrasenaActionPerformed
        // pressing enter on the password does the same as clicking the button
        ingresar();
    }//GEN-LAST:event_pwdContrasenaActionPerformed

    /** Validates the fields, performs the login and opens the screen of the role. */
    private void ingresar() {
        String usuario = txtUsuario.getText().trim();
        String contrasena = new String(pwdContrasena.getPassword());

        // make sure no field was left empty
        if (usuario.isEmpty() || contrasena.isEmpty()) {
            IblMensaje.setText("Debe llenar los dos campos");
            return;
        }

        boolean entro;
        if (rbAdmin.isSelected()) {
            entro = SesionActual.iniciarSesionAdmin(usuario, contrasena);
        } else {
            entro = SesionActual.iniciarSesionEmpleado(usuario, contrasena);
        }

        if (!entro) {
            IblMensaje.setText("Usuario o contraseña incorrectos");
            pwdContrasena.setText("");
            return;
        }

        IblMensaje.setText(" ");
        abrirVentana();
    }

    /** Opens the JFrame that matches the role of the current session. */
    private void abrirVentana() {
        javax.swing.JFrame ventana;

        if (SesionActual.esAdmin()) {
            ventana = new FrmAdmin();
        } else {
            String prefijo = SesionActual.getPrefijo();
            if ("SAL".equals(prefijo)) {
                ventana = new FrmSalonero();
            } else if ("COS".equals(prefijo)) {
                ventana = new FrmCocinero();
            } else if ("BAR".equals(prefijo)) {
                ventana = new FrmBartender();
            } else if ("CAJ".equals(prefijo)) {
                ventana = new FrmCajero();
            } else {
                // in case that user type has no screen yet
                JOptionPane.showMessageDialog(this,
                        "El rol " + SesionActual.getRol() + " no tiene pantalla asignada.",
                        "Aviso", JOptionPane.WARNING_MESSAGE);
                SesionActual.cerrarSesion();
                return;
            }
        }

        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose(); // close the login window
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblContrasena;
    private javax.swing.JLabel IblLogo;
    private javax.swing.JLabel IblMensaje;
    private javax.swing.JLabel IblTitulo;
    private javax.swing.JLabel IblUsuario;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JPasswordField pwdContrasena;
    private javax.swing.JRadioButton rbAdmin;
    private javax.swing.JRadioButton rbEmpleado;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
