/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author valer
 */
public class FrmSalonero extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSalonero.class.getName());

    /**
     * Creates new form FrmSalonero
     */
    public FrmSalonero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IblBienvenidaSal = new javax.swing.JLabel();
        IblSeccionAsignada = new javax.swing.JLabel();
        btnCerrarSesionSal = new javax.swing.JButton();
        tabSalonero = new javax.swing.JTabbedPane();
        pnlMesasComanda = new javax.swing.JPanel();
        cmbMesaAsignada = new javax.swing.JComboBox<>();
        txtCodigoPlato = new javax.swing.JTextField();
        txtNombrePlato = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        spnCantidadPlato = new javax.swing.JSpinner();
        btnAgregarPlato = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoBebida = new javax.swing.JTextField();
        txtNombreBebida = new javax.swing.JTextField();
        spnCantidadBebida = new javax.swing.JSpinner();
        btnAgregarBebida = new javax.swing.JButton();
        scrOrdenActual = new javax.swing.JScrollPane();
        tblOrdenActual = new javax.swing.JTable();
        btnQuitarItem = new javax.swing.JButton();
        btnGenerarComanda = new javax.swing.JButton();
        pnlMisComandas = new javax.swing.JPanel();
        scrMisComandas = new javax.swing.JScrollPane();
        tblMisComandas = new javax.swing.JTable();
        pnlNotificacion = new javax.swing.JPanel();
        lblNotificacion = new javax.swing.JLabel();
        btnVerDetalleComanda = new javax.swing.JButton();
        btnCerrarComanda = new javax.swing.JButton();
        btnRefrescarComandas = new javax.swing.JButton();
        pnlReservas = new javax.swing.JPanel();
        scrReservas = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaReserva = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHoraReserva = new javax.swing.JTextField();
        spnCantidadPersonas = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        chkIncluyeNinos = new javax.swing.JCheckBox();
        btnConsultarDisponibilidad = new javax.swing.JButton();
        btnGuardarReserva = new javax.swing.JButton();
        btnCancelarReserva = new javax.swing.JButton();
        btnLimpiarReserva = new javax.swing.JButton();
        pnlDisponibilidad = new javax.swing.JPanel();
        IblDisponibilidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IblBienvenidaSal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IblBienvenidaSal.setText("Salonero: Ana Solís");

        IblSeccionAsignada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblSeccionAsignada.setText("Sección asignada hoy: Sección A");

        btnCerrarSesionSal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesionSal.setText("Cerrar Sesión");

        cmbMesaAsignada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbMesaAsignada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mesa 1", "Mesa 2", "Mesa 3", "Mesa 4" }));

        txtNombrePlato.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Código Plato");

        spnCantidadPlato.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));

        btnAgregarPlato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarPlato.setText("Agregar Plato");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Código Bebida");

        txtNombreBebida.setEditable(false);

        spnCantidadBebida.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));

        btnAgregarBebida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarBebida.setText("Agregar Bebida");

        tblOrdenActual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tipo", "Ítem", "Cantidad"
            }
        ));
        scrOrdenActual.setViewportView(tblOrdenActual);

        btnQuitarItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuitarItem.setText("Quitar Ítem");

        btnGenerarComanda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGenerarComanda.setText("Generar Comanda ");

        javax.swing.GroupLayout pnlMesasComandaLayout = new javax.swing.GroupLayout(pnlMesasComanda);
        pnlMesasComanda.setLayout(pnlMesasComandaLayout);
        pnlMesasComandaLayout.setHorizontalGroup(
            pnlMesasComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMesasComandaLayout.createSequentialGroup()
                .addComponent(btnAgregarBebida)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlMesasComandaLayout.createSequentialGroup()
                .addGroup(pnlMesasComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPlato)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreBebida)
                    .addComponent(txtCodigoBebida)
                    .addComponent(spnCantidadPlato)
                    .addComponent(txtNombrePlato)
                    .addComponent(txtCodigoPlato)
                    .addComponent(cmbMesaAsignada, 0, 270, Short.MAX_VALUE)
                    .addComponent(spnCantidadBebida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(pnlMesasComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMesasComandaLayout.createSequentialGroup()
                        .addComponent(btnQuitarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnGenerarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrOrdenActual, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlMesasComandaLayout.setVerticalGroup(
            pnlMesasComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMesasComandaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlMesasComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMesasComandaLayout.createSequentialGroup()
                        .addComponent(cmbMesaAsignada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombrePlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnCantidadPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarPlato)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnCantidadBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarBebida))
                    .addGroup(pnlMesasComandaLayout.createSequentialGroup()
                        .addComponent(scrOrdenActual, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlMesasComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGenerarComanda)
                            .addComponent(btnQuitarItem))))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        tabSalonero.addTab("Mesas y Comandas", pnlMesasComanda);

        tblMisComandas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblMisComandas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número Comanda ", "Mesa", "Hora Orden", "Estado"
            }
        ));
        scrMisComandas.setViewportView(tblMisComandas);

        pnlNotificacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNotificacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnlNotificacionLayout = new javax.swing.GroupLayout(pnlNotificacion);
        pnlNotificacion.setLayout(pnlNotificacionLayout);
        pnlNotificacionLayout.setHorizontalGroup(
            pnlNotificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(508, Short.MAX_VALUE))
        );
        pnlNotificacionLayout.setVerticalGroup(
            pnlNotificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNotificacion)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        btnVerDetalleComanda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerDetalleComanda.setText("Detalle Comanda ");

        btnCerrarComanda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarComanda.setText("Cerrar Comanda");

        btnRefrescarComandas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefrescarComandas.setText("Refrescar Comandas ");

        javax.swing.GroupLayout pnlMisComandasLayout = new javax.swing.GroupLayout(pnlMisComandas);
        pnlMisComandas.setLayout(pnlMisComandasLayout);
        pnlMisComandasLayout.setHorizontalGroup(
            pnlMisComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMisComandasLayout.createSequentialGroup()
                .addGroup(pnlMisComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrMisComandas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMisComandasLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlMisComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMisComandasLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnVerDetalleComanda)
                                .addGap(18, 18, 18)
                                .addComponent(btnCerrarComanda)
                                .addGap(18, 18, 18)
                                .addComponent(btnRefrescarComandas)))))
                .addGap(65, 65, 65))
        );
        pnlMisComandasLayout.setVerticalGroup(
            pnlMisComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMisComandasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrMisComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(pnlMisComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefrescarComandas)
                    .addComponent(btnCerrarComanda)
                    .addComponent(btnVerDetalleComanda))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        tabSalonero.addTab("Mis Comandas ", pnlMisComandas);

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Fecha", "Hora", "Personas", "Estado"
            }
        ));
        scrReservas.setViewportView(tblReservas);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Teléfono:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Fecha:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Hora:");

        spnCantidadPersonas.setModel(new javax.swing.SpinnerNumberModel(2, 1, 20, 1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Personas");

        chkIncluyeNinos.setText("Incluye niños");

        btnConsultarDisponibilidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultarDisponibilidad.setText("Disponibilidad ");

        btnGuardarReserva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarReserva.setText("Guardar Reserva");

        btnCancelarReserva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarReserva.setText("Cancelar Reserva ");

        btnLimpiarReserva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiarReserva.setText("Limpiar Reserva");

        IblDisponibilidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnlDisponibilidadLayout = new javax.swing.GroupLayout(pnlDisponibilidad);
        pnlDisponibilidad.setLayout(pnlDisponibilidadLayout);
        pnlDisponibilidadLayout.setHorizontalGroup(
            pnlDisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDisponibilidadLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(IblDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        pnlDisponibilidadLayout.setVerticalGroup(
            pnlDisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDisponibilidadLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(IblDisponibilidad)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlReservasLayout = new javax.swing.GroupLayout(pnlReservas);
        pnlReservas.setLayout(pnlReservasLayout);
        pnlReservasLayout.setHorizontalGroup(
            pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReservasLayout.createSequentialGroup()
                .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlReservasLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(txtFechaReserva))
                    .addGroup(pnlReservasLayout.createSequentialGroup()
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(txtTelefonoCliente)))
                    .addGroup(pnlReservasLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(txtHoraReserva))
                    .addGroup(pnlReservasLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spnCantidadPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                    .addComponent(chkIncluyeNinos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReservasLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCancelarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultarDisponibilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReservasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addContainerGap())
        );
        pnlReservasLayout.setVerticalGroup(
            pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservasLayout.createSequentialGroup()
                .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReservasLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(scrReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtFechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReservasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtHoraReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReservasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(spnCantidadPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultarDisponibilidad)
                            .addComponent(btnGuardarReserva))
                        .addGap(18, 18, 18)
                        .addComponent(chkIncluyeNinos))
                    .addGroup(pnlReservasLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiarReserva)
                            .addComponent(btnCancelarReserva))))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        tabSalonero.addTab("Reservas", pnlReservas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(IblBienvenidaSal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IblSeccionAsignada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesionSal)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabSalonero, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(IblBienvenidaSal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblSeccionAsignada)
                    .addComponent(btnCerrarSesionSal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabSalonero, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmSalonero().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblBienvenidaSal;
    private javax.swing.JLabel IblDisponibilidad;
    private javax.swing.JLabel IblSeccionAsignada;
    private javax.swing.JButton btnAgregarBebida;
    private javax.swing.JButton btnAgregarPlato;
    private javax.swing.JButton btnCancelarReserva;
    private javax.swing.JButton btnCerrarComanda;
    private javax.swing.JButton btnCerrarSesionSal;
    private javax.swing.JButton btnConsultarDisponibilidad;
    private javax.swing.JButton btnGenerarComanda;
    private javax.swing.JButton btnGuardarReserva;
    private javax.swing.JButton btnLimpiarReserva;
    private javax.swing.JButton btnQuitarItem;
    private javax.swing.JButton btnRefrescarComandas;
    private javax.swing.JButton btnVerDetalleComanda;
    private javax.swing.JCheckBox chkIncluyeNinos;
    private javax.swing.JComboBox<String> cmbMesaAsignada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblNotificacion;
    private javax.swing.JPanel pnlDisponibilidad;
    private javax.swing.JPanel pnlMesasComanda;
    private javax.swing.JPanel pnlMisComandas;
    private javax.swing.JPanel pnlNotificacion;
    private javax.swing.JPanel pnlReservas;
    private javax.swing.JScrollPane scrMisComandas;
    private javax.swing.JScrollPane scrOrdenActual;
    private javax.swing.JScrollPane scrReservas;
    private javax.swing.JSpinner spnCantidadBebida;
    private javax.swing.JSpinner spnCantidadPersonas;
    private javax.swing.JSpinner spnCantidadPlato;
    private javax.swing.JTabbedPane tabSalonero;
    private javax.swing.JTable tblMisComandas;
    private javax.swing.JTable tblOrdenActual;
    private javax.swing.JTable tblReservas;
    private javax.swing.JTextField txtCodigoBebida;
    private javax.swing.JTextField txtCodigoPlato;
    private javax.swing.JTextField txtFechaReserva;
    private javax.swing.JTextField txtHoraReserva;
    private javax.swing.JTextField txtNombreBebida;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombrePlato;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
