/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import dao.AsignacionSeccionDAO;
import dao.BebidaDAO;
import dao.CategoriaBebidaDAO;
import dao.CategoriaComidaDAO;
import dao.ComandaDAO;
import dao.ComidaDAO;
import dao.DetalleComandaDAO;
import dao.FacturaDAO;
import dao.MesaDAO;
import dao.ProcesoBarDAO;
import dao.ProcesoCocinaDAO;
import dao.ReservaDAO;
import dao.SeccionSalonDAO;
import java.math.BigDecimal;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.AsignacionSeccion;
import model.Bebida;
import model.CategoriaBebida;
import model.CategoriaComida;
import model.Comanda;
import model.Comida;
import model.DetalleComanda;
import model.Factura;
import model.Mesa;
import model.ProcesoBar;
import model.ProcesoCocina;
import model.Reserva;
import model.SeccionSalon;
import session.SesionActual;

/**
 * Waiter screen: builds orders, reviews his own ones and handles reservations.
 *
 * @author valer
 */
public class FrmSalonero extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSalonero.class.getName());

    // an order has 20 minutes to be served
    private static final int LIMITE_MINUTOS = 20;

    // how many people fit at one table, used to know how many tables a reservation needs
    private static final int CAPACIDAD_MESA = 4;

    private final MesaDAO mesaDAO = new MesaDAO();
    private final ComidaDAO comidaDAO = new ComidaDAO();
    private final BebidaDAO bebidaDAO = new BebidaDAO();
    private final ComandaDAO comandaDAO = new ComandaDAO();
    private final DetalleComandaDAO detalleDAO = new DetalleComandaDAO();
    private final ReservaDAO reservaDAO = new ReservaDAO();
    private final AsignacionSeccionDAO asignacionDAO = new AsignacionSeccionDAO();
    private final SeccionSalonDAO seccionDAO = new SeccionSalonDAO();
    private final ProcesoCocinaDAO cocinaDAO = new ProcesoCocinaDAO();
    private final ProcesoBarDAO barDAO = new ProcesoBarDAO();
    private final FacturaDAO facturaDAO = new FacturaDAO();
    private final CategoriaComidaDAO categoriaComidaDAO = new CategoriaComidaDAO();
    private final CategoriaBebidaDAO categoriaBebidaDAO = new CategoriaBebidaDAO();

    // formats used to display the times
    private final DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    private final DateTimeFormatter formatoSoloHora = DateTimeFormatter.ofPattern("HH:mm");

    private List<Mesa> mesas = new ArrayList<>();            // tables of my own section
    private final List<DetalleComanda> orden = new ArrayList<>(); // items being added to the current order
    private List<Comanda> misComandas = new ArrayList<>();
    private List<Reserva> reservas = new ArrayList<>();

    // menu behind the combos: each list matches, row by row, what the combo shows
    private List<CategoriaComida> categoriasComida = new ArrayList<>();
    private List<CategoriaBebida> categoriasBebida = new ArrayList<>();
    private List<Comida> platosDelCombo = new ArrayList<>();
    private List<Bebida> bebidasDelCombo = new ArrayList<>();

    // true while the combos are being filled, so their events do not fire in the middle
    private boolean cargandoCombos = false;

    /**
     * Creates new form FrmSalonero
     */
    public FrmSalonero() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Restaurante - Salonero");

        // the tables are read only, they are not meant to be edited
        tblOrdenActual.setDefaultEditor(Object.class, null);
        tblMisComandas.setDefaultEditor(Object.class, null);
        tblReservas.setDefaultEditor(Object.class, null);

        cargarTodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IblBienvenidaSal = new javax.swing.JLabel();
        IblSeccionAsignada = new javax.swing.JLabel();
        btnCerrarSesionSal = new javax.swing.JButton();
        tabSalonero = new javax.swing.JTabbedPane();
        pnlMesasComanda = new javax.swing.JPanel();
        cmbMesaAsignada = new javax.swing.JComboBox<>();
        cmbCategoriaPlato = new javax.swing.JComboBox<>();
        cmbPlato = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        spnCantidadPlato = new javax.swing.JSpinner();
        btnAgregarPlato = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbCategoriaBebida = new javax.swing.JComboBox<>();
        cmbBebida = new javax.swing.JComboBox<>();
        spnCantidadBebida = new javax.swing.JSpinner();
        btnAgregarBebida = new javax.swing.JButton();
        scrOrdenActual = new javax.swing.JScrollPane();
        tblOrdenActual = new javax.swing.JTable();
        btnQuitarItem = new javax.swing.JButton();
        btnGenerarComanda = new javax.swing.JButton();
        pnlMisComandas = new javax.swing.JPanel();
        scrMisComandas = new javax.swing.JScrollPane();
        tblMisComandas = new javax.swing.JTable();
        pnlNotificacion = new javax.swing.JPanel();
        lblNotificacion = new javax.swing.JLabel();
        btnVerDetalleComanda = new javax.swing.JButton();
        btnCerrarComanda = new javax.swing.JButton();
        btnRefrescarComandas = new javax.swing.JButton();
        pnlReservas = new javax.swing.JPanel();
        scrReservas = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaReserva = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHoraReserva = new javax.swing.JTextField();
        spnCantidadPersonas = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        chkIncluyeNinos = new javax.swing.JCheckBox();
        btnConsultarDisponibilidad = new javax.swing.JButton();
        btnGuardarReserva = new javax.swing.JButton();
        btnCancelarReserva = new javax.swing.JButton();
        btnLimpiarReserva = new javax.swing.JButton();
        pnlDisponibilidad = new javax.swing.JPanel();
        IblDisponibilidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IblBienvenidaSal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IblBienvenidaSal.setText("Salonero: Ana Solís");

        IblSeccionAsignada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblSeccionAsignada.setText("Sección asignada hoy: Sección A");

        btnCerrarSesionSal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesionSal.setText("Cerrar Sesión");
        btnCerrarSesionSal.addActionListener(this::btnCerrarSesionSalActionPerformed);

        cmbMesaAsignada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbMesaAsignada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mesa 1", "Mesa 2", "Mesa 3", "Mesa 4" }));

        cmbCategoriaPlato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbCategoriaPlato.addActionListener(this::cmbCategoriaPlatoActionPerformed);

        cmbPlato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Plato (categoría y platillo)");

        spnCantidadPlato.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));

        btnAgregarPlato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarPlato.setText("Agregar Plato");
        btnAgregarPlato.addActionListener(this::btnAgregarPlatoActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Bebida (categoría y bebida)");

        cmbCategoriaBebida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbCategoriaBebida.addActionListener(this::cmbCategoriaBebidaActionPerformed);

        cmbBebida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        spnCantidadBebida.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));

        btnAgregarBebida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarBebida.setText("Agregar Bebida");
        btnAgregarBebida.addActionListener(this::btnAgregarBebidaActionPerformed);

        tblOrdenActual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Ítem", "Cantidad"
            }
        ));
        scrOrdenActual.setViewportView(tblOrdenActual);

        btnQuitarItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuitarItem.setText("Quitar Ítem");
        btnQuitarItem.addActionListener(this::btnQuitarItemActionPerformed);

        btnGenerarComanda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGenerarComanda.setText("Generar Comanda ");
        btnGenerarComanda.addActionListener(this::btnGenerarComandaActionPerformed);

        javax.swing.GroupLayout pnlMesasComandaLayout = new javax.swing.GroupLayout(pnlMesasComanda);
        pnlMesasComanda.setLayout(pnlMesasComandaLayout);
        pnlMesasComandaLayout.setHorizontalGroup(
            pnlMesasComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMesasComandaLayout.createSequentialGroup()
                .addComponent(btnAgregarBebida)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlMesasComandaLayout.createSequentialGroup()
                .addGroup(pnlMesasComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(btnAgregarPlato)
                    .addComponent(jLabel2)
                    .addComponent(cmbBebida, 0, 270, Short.MAX_VALUE)
                    .addComponent(cmbCategoriaBebida, 0, 270, Short.MAX_VALUE)
                    .addComponent(spnCantidadPlato)
                    .addComponent(cmbPlato, 0, 270, Short.MAX_VALUE)
                    .addComponent(cmbCategoriaPlato, 0, 270, Short.MAX_VALUE)
                    .addComponent(cmbMesaAsignada, 0, 270, Short.MAX_VALUE)
                    .addComponent(spnCantidadBebida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(pnlMesasComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrOrdenActual, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMesasComandaLayout.createSequentialGroup()
                        .addComponent(btnQuitarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGenerarComanda)))
                .addGap(14, 14, 14))
        );
        pnlMesasComandaLayout.setVerticalGroup(
            pnlMesasComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMesasComandaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlMesasComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMesasComandaLayout.createSequentialGroup()
                        .addComponent(cmbMesaAsignada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCategoriaPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnCantidadPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarPlato)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbCategoriaBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnCantidadBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarBebida))
                    .addGroup(pnlMesasComandaLayout.createSequentialGroup()
                        .addComponent(scrOrdenActual, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlMesasComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGenerarComanda)
                            .addComponent(btnQuitarItem))))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        tabSalonero.addTab("Mesas y Comandas", pnlMesasComanda);

        tblMisComandas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblMisComandas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número Comanda ", "Mesa", "Hora Orden", "Estado"
            }
        ));
        scrMisComandas.setViewportView(tblMisComandas);

        pnlNotificacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNotificacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnlNotificacionLayout = new javax.swing.GroupLayout(pnlNotificacion);
        pnlNotificacion.setLayout(pnlNotificacionLayout);
        pnlNotificacionLayout.setHorizontalGroup(
            pnlNotificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        pnlNotificacionLayout.setVerticalGroup(
            pnlNotificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNotificacion)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        btnVerDetalleComanda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerDetalleComanda.setText("Detalle Comanda ");
        btnVerDetalleComanda.addActionListener(this::btnVerDetalleComandaActionPerformed);

        btnCerrarComanda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarComanda.setText("Cerrar Comanda");
        btnCerrarComanda.addActionListener(this::btnCerrarComandaActionPerformed);

        btnRefrescarComandas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefrescarComandas.setText("Refrescar Comandas ");
        btnRefrescarComandas.addActionListener(this::btnRefrescarComandasActionPerformed);

        javax.swing.GroupLayout pnlMisComandasLayout = new javax.swing.GroupLayout(pnlMisComandas);
        pnlMisComandas.setLayout(pnlMisComandasLayout);
        pnlMisComandasLayout.setHorizontalGroup(
            pnlMisComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMisComandasLayout.createSequentialGroup()
                .addGroup(pnlMisComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrMisComandas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMisComandasLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlMisComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMisComandasLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnVerDetalleComanda)
                                .addGap(18, 18, 18)
                                .addComponent(btnCerrarComanda)
                                .addGap(18, 18, 18)
                                .addComponent(btnRefrescarComandas)))))
                .addGap(65, 65, 65))
        );
        pnlMisComandasLayout.setVerticalGroup(
            pnlMisComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMisComandasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrMisComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(pnlMisComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefrescarComandas)
                    .addComponent(btnCerrarComanda)
                    .addComponent(btnVerDetalleComanda))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        tabSalonero.addTab("Mis Comandas ", pnlMisComandas);

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Fecha", "Hora", "Personas", "Estado"
            }
        ));
        scrReservas.setViewportView(tblReservas);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Teléfono:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Fecha:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Hora:");

        spnCantidadPersonas.setModel(new javax.swing.SpinnerNumberModel(2, 1, 20, 1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Personas");

        chkIncluyeNinos.setText("Incluye niños");

        btnConsultarDisponibilidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultarDisponibilidad.setText("Disponibilidad ");
        btnConsultarDisponibilidad.addActionListener(this::btnConsultarDisponibilidadActionPerformed);

        btnGuardarReserva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarReserva.setText("Guardar Reserva");
        btnGuardarReserva.addActionListener(this::btnGuardarReservaActionPerformed);

        btnCancelarReserva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarReserva.setText("Cancelar Reserva ");
        btnCancelarReserva.addActionListener(this::btnCancelarReservaActionPerformed);

        btnLimpiarReserva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiarReserva.setText("Limpiar Reserva");
        btnLimpiarReserva.addActionListener(this::btnLimpiarReservaActionPerformed);

        IblDisponibilidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnlDisponibilidadLayout = new javax.swing.GroupLayout(pnlDisponibilidad);
        pnlDisponibilidad.setLayout(pnlDisponibilidadLayout);
        pnlDisponibilidadLayout.setHorizontalGroup(
            pnlDisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDisponibilidadLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(IblDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlDisponibilidadLayout.setVerticalGroup(
            pnlDisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDisponibilidadLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(IblDisponibilidad)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlReservasLayout = new javax.swing.GroupLayout(pnlReservas);
        pnlReservas.setLayout(pnlReservasLayout);
        pnlReservasLayout.setHorizontalGroup(
            pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReservasLayout.createSequentialGroup()
                .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlReservasLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(txtFechaReserva))
                    .addGroup(pnlReservasLayout.createSequentialGroup()
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(txtTelefonoCliente)))
                    .addGroup(pnlReservasLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(txtHoraReserva))
                    .addGroup(pnlReservasLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spnCantidadPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                    .addComponent(chkIncluyeNinos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReservasLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCancelarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultarDisponibilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReservasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addContainerGap())
        );
        pnlReservasLayout.setVerticalGroup(
            pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservasLayout.createSequentialGroup()
                .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReservasLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(scrReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtFechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReservasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtHoraReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReservasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(spnCantidadPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultarDisponibilidad)
                            .addComponent(btnGuardarReserva))
                        .addGap(18, 18, 18)
                        .addComponent(chkIncluyeNinos))
                    .addGroup(pnlReservasLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiarReserva)
                            .addComponent(btnCancelarReserva))))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        tabSalonero.addTab("Reservas", pnlReservas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(IblBienvenidaSal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IblSeccionAsignada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesionSal)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabSalonero, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(IblBienvenidaSal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblSeccionAsignada)
                    .addComponent(btnCerrarSesionSal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabSalonero, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionSalActionPerformed
        SesionActual.cerrarSesion();
        new FrmLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionSalActionPerformed

    private void cmbCategoriaPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaPlatoActionPerformed
        // changing the category redraws the list of dishes
        if (!cargandoCombos) {
            cargarPlatosDelCombo();
        }
    }//GEN-LAST:event_cmbCategoriaPlatoActionPerformed

    private void cmbCategoriaBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaBebidaActionPerformed
        // changing the category redraws the list of drinks
        if (!cargandoCombos) {
            cargarBebidasDelCombo();
        }
    }//GEN-LAST:event_cmbCategoriaBebidaActionPerformed

    private void btnAgregarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPlatoActionPerformed
        int fila = cmbPlato.getSelectedIndex();
        if (fila < 0 || fila >= platosDelCombo.size()) {
            JOptionPane.showMessageDialog(this, "Escoja un plato de la lista.");
            return;
        }
        Comida comida = platosDelCombo.get(fila);
        agregarItem("comida", comida.getId_comida(), (Integer) spnCantidadPlato.getValue(), comida.getPrecio());
        spnCantidadPlato.setValue(1);
    }//GEN-LAST:event_btnAgregarPlatoActionPerformed

    private void btnAgregarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarBebidaActionPerformed
        int fila = cmbBebida.getSelectedIndex();
        if (fila < 0 || fila >= bebidasDelCombo.size()) {
            JOptionPane.showMessageDialog(this, "Escoja una bebida de la lista.");
            return;
        }
        Bebida bebida = bebidasDelCombo.get(fila);
        agregarItem("bebida", bebida.getId_bebida(), (Integer) spnCantidadBebida.getValue(), bebida.getPrecio());
        spnCantidadBebida.setValue(1);
    }//GEN-LAST:event_btnAgregarBebidaActionPerformed

    private void btnQuitarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarItemActionPerformed
        int fila = tblOrdenActual.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione el ítem que quiere quitar.");
            return;
        }
        orden.remove(fila);
        pintarOrden();
    }//GEN-LAST:event_btnQuitarItemActionPerformed

    private void btnGenerarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarComandaActionPerformed
        generarComanda();
    }//GEN-LAST:event_btnGenerarComandaActionPerformed

    private void btnRefrescarComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarComandasActionPerformed
        cargarMisComandas();
    }//GEN-LAST:event_btnRefrescarComandasActionPerformed

    private void btnVerDetalleComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleComandaActionPerformed
        verDetalleComanda();
    }//GEN-LAST:event_btnVerDetalleComandaActionPerformed

    private void btnCerrarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarComandaActionPerformed
        cerrarComanda();
    }//GEN-LAST:event_btnCerrarComandaActionPerformed

    private void btnConsultarDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarDisponibilidadActionPerformed
        consultarDisponibilidad();
    }//GEN-LAST:event_btnConsultarDisponibilidadActionPerformed

    private void btnGuardarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarReservaActionPerformed
        guardarReserva();
    }//GEN-LAST:event_btnGuardarReservaActionPerformed

    private void btnCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarReservaActionPerformed
        cancelarReserva();
    }//GEN-LAST:event_btnCancelarReservaActionPerformed

    private void btnLimpiarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarReservaActionPerformed
        limpiarReserva();
    }//GEN-LAST:event_btnLimpiarReservaActionPerformed

    // ------------------ data loading ------------------

    /** Fills the screen with the data of the waiter who logged in. */
    private void cargarTodo() {
        if (SesionActual.getUsuario() == null) {
            return; // in case the window is opened without logging in first
        }
        IblBienvenidaSal.setText("Salonero: " + SesionActual.getNombre());
        IblDisponibilidad.setText("");
        txtFechaReserva.setText(LocalDate.now().toString());
        txtHoraReserva.setText("19:00");
        cargarSeccionYMesas();
        cargarMenu();
        cargarMisComandas();
        cargarReservas();
    }

    /**
     * Fills the menu combos: first the categories and then the items of the selected one,
     * so the waiter picks from the menu instead of remembering codes.
     */
    private void cargarMenu() {
        cargandoCombos = true;

        categoriasComida = categoriaComidaDAO.findAll();
        cmbCategoriaPlato.removeAllItems();
        cmbCategoriaPlato.addItem("Todas las categorías");
        for (CategoriaComida c : categoriasComida) {
            cmbCategoriaPlato.addItem(c.getNombre());
        }

        categoriasBebida = categoriaBebidaDAO.findAll();
        cmbCategoriaBebida.removeAllItems();
        cmbCategoriaBebida.addItem("Todas las categorías");
        for (CategoriaBebida c : categoriasBebida) {
            cmbCategoriaBebida.addItem(c.getNombre());
        }

        cargandoCombos = false;

        cargarPlatosDelCombo();
        cargarBebidasDelCombo();
    }

    /** Shows the dishes of the chosen category, only the ones available today. */
    private void cargarPlatosDelCombo() {
        // the first option of the combo is "all categories", the rest follow the list order
        int fila = cmbCategoriaPlato.getSelectedIndex();
        int idCategoria = fila > 0 ? categoriasComida.get(fila - 1).getId_categoria() : 0;

        platosDelCombo = new ArrayList<>();
        cargandoCombos = true;
        cmbPlato.removeAllItems();
        for (Comida c : comidaDAO.findAll()) {
            if (c.getActivo() == 0) {
                continue; // not available today
            }
            if (idCategoria > 0 && c.getId_categoria() != idCategoria) {
                continue; // it is from another category
            }
            platosDelCombo.add(c);
            cmbPlato.addItem(c.getNombre() + "   ₡" + c.getPrecio());
        }
        cargandoCombos = false;
    }

    /** Shows the drinks of the chosen category, only the ones available today. */
    private void cargarBebidasDelCombo() {
        int fila = cmbCategoriaBebida.getSelectedIndex();
        int idCategoria = fila > 0 ? categoriasBebida.get(fila - 1).getId_categoria() : 0;

        bebidasDelCombo = new ArrayList<>();
        cargandoCombos = true;
        cmbBebida.removeAllItems();
        for (Bebida b : bebidaDAO.findAll()) {
            if (b.getActivo() == 0) {
                continue;
            }
            if (idCategoria > 0 && b.getId_categoria() != idCategoria) {
                continue;
            }
            bebidasDelCombo.add(b);
            cmbBebida.addItem(b.getNombre() + "   ₡" + b.getPrecio());
        }
        cargandoCombos = false;
    }

    /** Finds the section assigned for today and fills the combo with its tables. */
    private void cargarSeccionYMesas() {
        cmbMesaAsignada.removeAllItems();
        mesas = new ArrayList<>();

        AsignacionSeccion asignacion = asignacionDAO.findBySaloneroFecha(SesionActual.getCodigo(), LocalDate.now());
        if (asignacion == null) {
            IblSeccionAsignada.setText("Sección asignada hoy: ninguna");
            return;
        }

        SeccionSalon seccion = seccionDAO.findById(asignacion.getIdSeccion());
        IblSeccionAsignada.setText("Sección asignada hoy: " + (seccion != null ? seccion.getNombre() : "?"));

        mesas = mesaDAO.findBySeccion(asignacion.getIdSeccion());
        for (Mesa m : mesas) {
            String estado = m.getDisponible() == 1 ? "libre" : "ocupada";
            cmbMesaAsignada.addItem("Mesa " + m.getNumero_mesa() + " (" + estado + ")");
        }
    }

    /** Loads my orders and warns when any of them went over the 20 minutes. */
    private void cargarMisComandas() {
        misComandas = comandaDAO.findByEmpleado(SesionActual.getCodigo());
        List<Mesa> todasLasMesas = mesaDAO.findAll();

        DefaultTableModel modelo = (DefaultTableModel) tblMisComandas.getModel();
        modelo.setRowCount(0);

        int atrasadas = 0;
        for (Comanda c : misComandas) {
            String hora = c.getHora_orden() != null ? c.getHora_orden().format(formatoHora) : "";
            modelo.addRow(new Object[]{c.getId_comanda(), nombreMesa(todasLasMesas, c.getId_mesa()), hora, c.getEstado()});
            if (minutosDeAtraso(c) > LIMITE_MINUTOS) {
                atrasadas++;
            }
        }

        pintarNotificacion(todasLasMesas, atrasadas);
    }

    /**
     * Builds the notice of the orders that are ready. For each one it shows the table,
     * the time the kitchen or the bar finished it, and what is ready to be served.
     */
    private void pintarNotificacion(List<Mesa> todasLasMesas, int atrasadas) {
        String aviso = "";
        int listas = 0;

        for (Comanda c : misComandas) {
            if (!"lista".equals(c.getEstado())) {
                continue;
            }
            listas++;
            if (listas > 3) {
                continue; // keep the panel short, the remaining ones are summarized below
            }
            aviso = aviso + "PEDIDO LISTO &nbsp;|&nbsp; " + nombreMesa(todasLasMesas, c.getId_mesa())
                    + " &nbsp;|&nbsp; comanda #" + c.getId_comanda()
                    + " &nbsp;|&nbsp; " + horaNotificacion(c.getId_comanda())
                    + "<br>&nbsp;&nbsp;&nbsp;&nbsp;" + queEstaListo(c.getId_comanda()) + "<br>";
        }

        if (listas > 3) {
            aviso = aviso + "y " + (listas - 3) + " pedido(s) más listos<br>";
        }

        if (listas > 0) {
            lblNotificacion.setForeground(new java.awt.Color(0, 100, 0));
            if (atrasadas > 0) {
                aviso = aviso + "<font color='red'>Atención: " + atrasadas
                        + " comanda(s) pasaron los " + LIMITE_MINUTOS + " minutos</font>";
            }
            lblNotificacion.setText("<html>" + aviso + "</html>");
        } else if (atrasadas > 0) {
            lblNotificacion.setForeground(java.awt.Color.RED);
            lblNotificacion.setText("Atención: " + atrasadas + " comanda(s) pasaron los " + LIMITE_MINUTOS + " minutos");
        } else {
            lblNotificacion.setForeground(new java.awt.Color(0, 128, 0));
            lblNotificacion.setText("No hay pedidos listos por servir");
        }
    }

    /** Time the order was finished, taking the later one between the kitchen and the bar. */
    private String horaNotificacion(int idComanda) {
        LocalDateTime hora = null;
        ProcesoCocina pc = cocinaDAO.findByComanda(idComanda);
        if (pc != null && pc.getHora_lista() != null) {
            hora = pc.getHora_lista();
        }
        ProcesoBar pb = barDAO.findByComanda(idComanda);
        if (pb != null && pb.getHora_lista() != null && (hora == null || pb.getHora_lista().isAfter(hora))) {
            hora = pb.getHora_lista();
        }
        return hora != null ? "listo a las " + hora.format(formatoSoloHora) : "sin hora";
    }

    /** Lists the dishes and drinks that are ready in that order. */
    private String queEstaListo(int idComanda) {
        String platos = "";
        String bebidas = "";
        for (DetalleComanda d : detalleDAO.findByComanda(idComanda)) {
            String linea = d.getCantidad() + " " + detalleDAO.getNombreItem(d);
            if ("comida".equals(d.getTipo_item())) {
                platos = platos.isEmpty() ? linea : platos + ", " + linea;
            } else {
                bebidas = bebidas.isEmpty() ? linea : bebidas + ", " + linea;
            }
        }
        String texto = "";
        if (!platos.isEmpty()) {
            texto = "Platillos: " + platos;
        }
        if (!bebidas.isEmpty()) {
            texto = texto.isEmpty() ? "Bebidas: " + bebidas : texto + " &nbsp;·&nbsp; Bebidas: " + bebidas;
        }
        return texto;
    }

    /** Fills the reservations table. */
    private void cargarReservas() {
        reservas = reservaDAO.findAll();
        DefaultTableModel modelo = (DefaultTableModel) tblReservas.getModel();
        modelo.setRowCount(0);
        for (Reserva r : reservas) {
            modelo.addRow(new Object[]{
                r.getId_reserva(), r.getNombre_cliente(), r.getFecha_reserva(),
                r.getHora_reserva(), r.getCantidad_pers(), r.getEstado()
            });
        }
    }

    // ------------------ orders ------------------

    /** Adds one item to the order being built; it is not saved to the database yet. */
    private void agregarItem(String tipo, int idItem, int cantidad, BigDecimal precio) {
        DetalleComanda detalle = new DetalleComanda();
        detalle.setTipo_item(tipo);
        detalle.setId_item(idItem);
        detalle.setCantidad(cantidad);
        detalle.setPrecio_unit(precio);
        orden.add(detalle);
        pintarOrden();
    }

    /** Redraws the table of the order being built. */
    private void pintarOrden() {
        DefaultTableModel modelo = (DefaultTableModel) tblOrdenActual.getModel();
        modelo.setRowCount(0);
        for (DetalleComanda d : orden) {
            modelo.addRow(new Object[]{d.getTipo_item(), detalleDAO.getNombreItem(d), d.getCantidad()});
        }
    }

    /** Saves the order with its details and sends it to the kitchen and/or the bar. */
    private void generarComanda() {
        int fila = cmbMesaAsignada.getSelectedIndex();
        if (fila < 0 || mesas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No tiene mesas asignadas para hoy.");
            return;
        }
        if (orden.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Agregue al menos un plato o una bebida.");
            return;
        }

        Mesa mesa = mesas.get(fila);

        Comanda comanda = new Comanda();
        comanda.setORIGEN("salon");
        comanda.setCodigo_emp(SesionActual.getCodigo());
        comanda.setId_mesa(mesa.getId_mesa());
        comanda.setHora_orden(LocalDateTime.now());
        comanda.setEstado("abierta");

        int idComanda = comandaDAO.insertGetId(comanda);
        if (idComanda <= 0) {
            JOptionPane.showMessageDialog(this, "No se pudo guardar la comanda.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean hayComida = false;
        boolean hayBebida = false;
        for (DetalleComanda d : orden) {
            d.setId_comanda(idComanda);
            detalleDAO.insert(d);
            if ("comida".equals(d.getTipo_item())) {
                hayComida = true;
            } else {
                hayBebida = true;
            }
        }

        // dishes go to the kitchen and drinks go to the bar
        if (hayComida) {
            ProcesoCocina pc = new ProcesoCocina();
            pc.setId_comanda(idComanda);
            pc.setHora_recibida(LocalDateTime.now());
            cocinaDAO.insert(pc);
        }
        if (hayBebida) {
            ProcesoBar pb = new ProcesoBar();
            pb.setId_comanda(idComanda);
            pb.setHora_recibida(LocalDateTime.now());
            barDAO.insert(pb);
        }

        // the table becomes busy
        mesa.setDisponible(0);
        mesaDAO.update(mesa);

        JOptionPane.showMessageDialog(this, "Comanda #" + idComanda + " generada para la mesa " + mesa.getNumero_mesa());

        orden.clear();
        pintarOrden();
        cargarSeccionYMesas();
        cargarMisComandas();
    }

    /** Shows the items and the total of the selected order. */
    private void verDetalleComanda() {
        int fila = tblMisComandas.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una comanda de la tabla.");
            return;
        }

        Comanda comanda = misComandas.get(fila);
        List<DetalleComanda> detalles = detalleDAO.findByComanda(comanda.getId_comanda());

        String texto = "Comanda #" + comanda.getId_comanda() + "  (" + comanda.getEstado() + ")\n\n";
        BigDecimal total = BigDecimal.ZERO;
        for (DetalleComanda d : detalles) {
            BigDecimal linea = d.getPrecio_unit().multiply(new BigDecimal(d.getCantidad()));
            total = total.add(linea);
            texto += d.getCantidad() + " x " + detalleDAO.getNombreItem(d) + "   ₡" + linea + "\n";
        }
        texto += "\nSubtotal: ₡" + total;

        long minutos = minutosDeAtraso(comanda);
        if (minutos > LIMITE_MINUTOS) {
            texto += "\n\nEsta comanda lleva " + minutos + " minutos abierta (el límite son " + LIMITE_MINUTOS + ").";
        }

        JOptionPane.showMessageDialog(this, texto, "Detalle de la comanda", JOptionPane.INFORMATION_MESSAGE);
    }

    /** Closes the selected order and frees its table again. */
    private void cerrarComanda() {
        int fila = tblMisComandas.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una comanda de la tabla.");
            return;
        }

        Comanda comanda = misComandas.get(fila);
        if ("cerrada".equals(comanda.getEstado())) {
            JOptionPane.showMessageDialog(this, "Esa comanda ya está cerrada.");
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Cerrar la comanda #" + comanda.getId_comanda() + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }

        if (!comandaDAO.updateEstado(comanda.getId_comanda(), "cerrada")) {
            JOptionPane.showMessageDialog(this, "No se pudo cerrar la comanda.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // free the table
        for (Mesa m : mesaDAO.findAll()) {
            if (m.getId_mesa() == comanda.getId_mesa()) {
                m.setDisponible(1);
                mesaDAO.update(m);
            }
        }

        generarFacturaProvisional(comanda);

        cargarSeccionYMesas();
        cargarMisComandas();
    }

    /**
     * Closing the order issues the provisional invoice, which is the one the customer
     * sees and the one that later goes to the cashier to be paid.
     */
    private void generarFacturaProvisional(Comanda comanda) {
        // do not issue a second provisional invoice if there is one already
        for (Factura f : facturaDAO.findByComanda(comanda.getId_comanda())) {
            if ("provisional".equals(f.getTipo())) {
                return;
            }
        }

        List<DetalleComanda> detalles = detalleDAO.findByComanda(comanda.getId_comanda());
        BigDecimal subtotal = BigDecimal.ZERO;
        String lineas = "";
        for (DetalleComanda d : detalles) {
            BigDecimal linea = d.getPrecio_unit().multiply(new BigDecimal(d.getCantidad()));
            subtotal = subtotal.add(linea);
            lineas = lineas + d.getCantidad() + " x " + detalleDAO.getNombreItem(d) + "   ₡" + linea + "\n";
        }

        Factura factura = new Factura();
        factura.setId_comanda(comanda.getId_comanda());
        factura.setCodigo_cajero(SesionActual.getCodigo()); // who issued it
        factura.setFecha_emision(LocalDateTime.now());
        factura.setSubtotal(subtotal); // the DAO computes the sales tax
        factura.setTipo("provisional");
        factura.setEstado("pendiente");

        int idFactura = facturaDAO.insertGetId(factura);
        if (idFactura <= 0) {
            JOptionPane.showMessageDialog(this, "La comanda se cerró pero no se pudo sacar la factura provisional.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this,
                "FACTURA PROVISIONAL #" + idFactura + "\n"
                + "Comanda #" + comanda.getId_comanda() + "   Mesa " + numeroDeMesa(comanda.getId_mesa()) + "\n"
                + "Salonero: " + SesionActual.getNombre() + "\n\n"
                + lineas + "\n"
                + "Total antes de impuesto: ₡" + factura.getSubtotal() + "\n"
                + "IVA (13%): ₡" + factura.getImpuesto() + "\n"
                + "Total a pagar: ₡" + factura.getTotal() + "\n\n"
                + "Pasa a caja para ser cancelada.",
                "Factura provisional", JOptionPane.INFORMATION_MESSAGE);
    }

    /** Returns the table number, looking it up in the database. */
    private String numeroDeMesa(int idMesa) {
        for (Mesa m : mesaDAO.findAll()) {
            if (m.getId_mesa() == idMesa) {
                return String.valueOf(m.getNumero_mesa());
            }
        }
        return "-";
    }

    // ------------------ reservations ------------------

    /**
     * Reservation preview: it shows which tables are free at that date and time,
     * how many are needed for the party size and, when there is no room,
     * at what time a table becomes free.
     */
    private void consultarDisponibilidad() {
        LocalDate fecha = leerFecha(txtFechaReserva.getText().trim());
        LocalTime hora = leerHora(txtHoraReserva.getText().trim());
        if (fecha == null || hora == null) {
            JOptionPane.showMessageDialog(this, "Revise la fecha (aaaa-mm-dd) y la hora (hh:mm).");
            return;
        }

        int personas = (Integer) spnCantidadPersonas.getValue();
        int mesasNecesarias = mesasQueOcupa(personas);
        List<Mesa> libres = reservaDAO.findMesasLibres(fecha, hora);

        if (libres.size() >= mesasNecesarias) {
            IblDisponibilidad.setForeground(new java.awt.Color(0, 100, 0));
            IblDisponibilidad.setText("<html>Sí hay campo a las " + hora.format(formatoSoloHora)
                    + "<br>" + personas + " personas ocupan " + mesasNecesarias + " mesa(s)"
                    + "<br>Mesas libres: " + listaDeMesas(libres) + "</html>");
        } else {
            LocalTime proxima = reservaDAO.proximaHoraLibre(fecha, hora, mesasNecesarias);
            IblDisponibilidad.setForeground(java.awt.Color.RED);
            String texto = "<html>No hay campo a las " + hora.format(formatoSoloHora)
                    + "<br>Se necesitan " + mesasNecesarias + " mesa(s) y solo hay " + libres.size();
            if (proxima != null) {
                texto = texto + "<br>Queda mesa a las " + proxima.format(formatoSoloHora);
            } else {
                texto = texto + "<br>Ese día ya no queda campo";
            }
            IblDisponibilidad.setText(texto + "</html>");
        }
    }

    /** Saves a new reservation and assigns it a free table. */
    private void guardarReserva() {
        String nombre = txtNombreCliente.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escriba el nombre del cliente.");
            return;
        }

        LocalDate fecha = leerFecha(txtFechaReserva.getText().trim());
        if (fecha == null) {
            JOptionPane.showMessageDialog(this, "La fecha debe ser aaaa-mm-dd (ejemplo " + LocalDate.now() + ").");
            return;
        }

        LocalTime hora = leerHora(txtHoraReserva.getText().trim());
        if (hora == null) {
            JOptionPane.showMessageDialog(this, "La hora debe ser hh:mm (ejemplo 19:30).");
            return;
        }

        int personas = (Integer) spnCantidadPersonas.getValue();
        int mesasNecesarias = mesasQueOcupa(personas);
        List<Mesa> libres = reservaDAO.findMesasLibres(fecha, hora);

        // check there is a table before saving
        if (libres.size() < mesasNecesarias) {
            LocalTime proxima = reservaDAO.proximaHoraLibre(fecha, hora, mesasNecesarias);
            String mensaje = "No hay mesa para " + personas + " persona(s) a las " + hora.format(formatoSoloHora) + ".";
            if (proxima != null) {
                mensaje = mensaje + "\nLa próxima hora con campo es a las " + proxima.format(formatoSoloHora) + ".";
            } else {
                mensaje = mensaje + "\nEse día ya no queda campo; puede esperar en el bar.";
            }
            JOptionPane.showMessageDialog(this, mensaje, "Sin disponibilidad", JOptionPane.WARNING_MESSAGE);
            consultarDisponibilidad();
            return;
        }

        Mesa asignada = libres.get(0);

        Reserva reserva = new Reserva();
        reserva.setNombre_cliente(nombre);
        reserva.setTelefono(txtTelefonoCliente.getText().trim());
        reserva.setFecha_reserva(fecha);
        reserva.setHora_reserva(hora);
        reserva.setCantidad_pers(personas);
        reserva.setIncluye_ninos(chkIncluyeNinos.isSelected());
        reserva.setId_mesa(asignada.getId_mesa());
        reserva.setEstado("pendiente");

        if (reservaDAO.insert(reserva)) {
            JOptionPane.showMessageDialog(this, "Reserva guardada en la mesa " + asignada.getNumero_mesa() + ".");
            limpiarReserva();
            cargarReservas();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo guardar la reserva.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** How many tables a party needs, based on how many people fit at one table. */
    private int mesasQueOcupa(int personas) {
        int mesas = personas / CAPACIDAD_MESA;
        if (personas % CAPACIDAD_MESA > 0) {
            mesas++;
        }
        return mesas;
    }

    /** Builds the text with the table numbers, trimming the list when there are many. */
    private String listaDeMesas(List<Mesa> mesasLibres) {
        String texto = "";
        for (int i = 0; i < mesasLibres.size() && i < 8; i++) {
            texto = texto.isEmpty() ? "" + mesasLibres.get(i).getNumero_mesa()
                                    : texto + ", " + mesasLibres.get(i).getNumero_mesa();
        }
        if (mesasLibres.size() > 8) {
            texto = texto + " y " + (mesasLibres.size() - 8) + " más";
        }
        return texto;
    }

    /** Sets the selected reservation as cancelled. */
    private void cancelarReserva() {
        int fila = tblReservas.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una reserva de la tabla.");
            return;
        }

        Reserva reserva = reservas.get(fila);
        if ("cancelada".equals(reserva.getEstado())) {
            JOptionPane.showMessageDialog(this, "Esa reserva ya está cancelada.");
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Cancelar la reserva de " + reserva.getNombre_cliente() + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }

        if (reservaDAO.updateEstado(reserva.getId_reserva(), "cancelada")) {
            cargarReservas();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo cancelar la reserva.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** Clears the reservation fields. */
    private void limpiarReserva() {
        txtNombreCliente.setText("");
        txtTelefonoCliente.setText("");
        txtFechaReserva.setText(LocalDate.now().toString());
        txtHoraReserva.setText("19:00");
        spnCantidadPersonas.setValue(2);
        chkIncluyeNinos.setSelected(false);
        IblDisponibilidad.setText("");
        tblReservas.clearSelection();
    }

    // ------------------ helpers ------------------

    /** Minutes the order has been open, or 0 when it is already closed. */
    private long minutosDeAtraso(Comanda comanda) {
        if ("cerrada".equals(comanda.getEstado()) || comanda.getHora_orden() == null) {
            return 0;
        }
        return Duration.between(comanda.getHora_orden(), LocalDateTime.now()).toMinutes();
    }

    /** Finds the table number in the list, so the raw id is not displayed. */
    private String nombreMesa(List<Mesa> lista, int idMesa) {
        for (Mesa m : lista) {
            if (m.getId_mesa() == idMesa) {
                return "Mesa " + m.getNumero_mesa();
            }
        }
        return "-";
    }

    /** Converts the text into a date, or null when it is not well written. */
    private LocalDate leerFecha(String texto) {
        try {
            return LocalDate.parse(texto);
        } catch (Exception e) {
            return null;
        }
    }

    /** Converts the text into a time, or null when it is not well written. */
    private LocalTime leerHora(String texto) {
        try {
            return LocalTime.parse(texto);
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmSalonero().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblBienvenidaSal;
    private javax.swing.JLabel IblDisponibilidad;
    private javax.swing.JLabel IblSeccionAsignada;
    private javax.swing.JButton btnAgregarBebida;
    private javax.swing.JButton btnAgregarPlato;
    private javax.swing.JButton btnCancelarReserva;
    private javax.swing.JButton btnCerrarComanda;
    private javax.swing.JButton btnCerrarSesionSal;
    private javax.swing.JButton btnConsultarDisponibilidad;
    private javax.swing.JButton btnGenerarComanda;
    private javax.swing.JButton btnGuardarReserva;
    private javax.swing.JButton btnLimpiarReserva;
    private javax.swing.JButton btnQuitarItem;
    private javax.swing.JButton btnRefrescarComandas;
    private javax.swing.JButton btnVerDetalleComanda;
    private javax.swing.JCheckBox chkIncluyeNinos;
    private javax.swing.JComboBox<String> cmbBebida;
    private javax.swing.JComboBox<String> cmbCategoriaBebida;
    private javax.swing.JComboBox<String> cmbCategoriaPlato;
    private javax.swing.JComboBox<String> cmbMesaAsignada;
    private javax.swing.JComboBox<String> cmbPlato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblNotificacion;
    private javax.swing.JPanel pnlDisponibilidad;
    private javax.swing.JPanel pnlMesasComanda;
    private javax.swing.JPanel pnlMisComandas;
    private javax.swing.JPanel pnlNotificacion;
    private javax.swing.JPanel pnlReservas;
    private javax.swing.JScrollPane scrMisComandas;
    private javax.swing.JScrollPane scrOrdenActual;
    private javax.swing.JScrollPane scrReservas;
    private javax.swing.JSpinner spnCantidadBebida;
    private javax.swing.JSpinner spnCantidadPersonas;
    private javax.swing.JSpinner spnCantidadPlato;
    private javax.swing.JTabbedPane tabSalonero;
    private javax.swing.JTable tblMisComandas;
    private javax.swing.JTable tblOrdenActual;
    private javax.swing.JTable tblReservas;
    private javax.swing.JTextField txtFechaReserva;
    private javax.swing.JTextField txtHoraReserva;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
